# Dependabot configuration file.
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"
