include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:

    # Separate the control structure expression from its statement.
    # http://dart-lang.github.io/linter/lints/always_put_control_body_on_new_line.html
    - always_put_control_body_on_new_line

    # Put @required named parameters first.
    # http://dart-lang.github.io/linter/lints/always_put_required_named_parameters_first.html
    - always_put_required_named_parameters_first

    # Don't explicitly catch Error or types that implement it.
    # http://dart-lang.github.io/linter/lints/avoid_catching_errors.html
    - avoid_catching_errors

    # Avoid defining a class that contains only static members.
    # http://dart-lang.github.io/linter/lints/avoid_classes_with_only_static_members.html
    - avoid_classes_with_only_static_members

    # Avoid double and int checks.
    # http://dart-lang.github.io/linter/lints/avoid_double_and_int_checks.html
    - avoid_double_and_int_checks

    # Avoid field initializers in const classes.
    # http://dart-lang.github.io/linter/lints/avoid_field_initializers_in_const_classes.html
    - avoid_field_initializers_in_const_classes

    # Don't implement classes that override `==`.
    # http://dart-lang.github.io/linter/lints/avoid_implementing_value_types.html
    - avoid_implementing_value_types

    # Avoid JavaScript rounded ints.
    # http://dart-lang.github.io/linter/lints/avoid_js_rounded_ints.html
    - avoid_js_rounded_ints

    # Avoid private typedef functions.
    # http://dart-lang.github.io/linter/lints/avoid_private_typedef_functions.html
    - avoid_private_typedef_functions

    # Avoid returning null from members whose return type is bool, double, int, or num.
    # http://dart-lang.github.io/linter/lints/avoid_returning_null.html
    - avoid_returning_null

    # Avoid returning null for Future.
    # http://dart-lang.github.io/linter/lints/avoid_returning_null_for_future.html
    - avoid_returning_null_for_future

    # Avoid returning this from methods just to enable a fluent interface.
    # http://dart-lang.github.io/linter/lints/avoid_returning_this.html
    - avoid_returning_this

    # Avoid setters without getters.
    # http://dart-lang.github.io/linter/lints/avoid_setters_without_getters.html
    - avoid_setters_without_getters

    # Avoid slow async `dart:io` methods.
    # http://dart-lang.github.io/linter/lints/avoid_slow_async_io.html
    - avoid_slow_async_io

    # Avoid defining unused parameters in constructors.
    # http://dart-lang.github.io/linter/lints/avoid_unused_constructor_parameters.html
    - avoid_unused_constructor_parameters

    # Avoid async functions that return void.
    # http://dart-lang.github.io/linter/lints/avoid_void_async.html
    - avoid_void_async

    # Cancel instances of dart.async.StreamSubscription.
    # http://dart-lang.github.io/linter/lints/cancel_subscriptions.html
    - cancel_subscriptions

    # Close instances of `dart.core.Sink`.
    # http://dart-lang.github.io/linter/lints/close_sinks.html
    - close_sinks

    # Only reference in scope identifiers in doc comments.
    # http://dart-lang.github.io/linter/lints/comment_references.html
    - comment_references

    # DO reference all public properties in debug methods.
    # http://dart-lang.github.io/linter/lints/diagnostic_describe_all_properties.html
    - diagnostic_describe_all_properties

    # Adhere to Effective Dart Guide directives sorting conventions.
    # http://dart-lang.github.io/linter/lints/directives_ordering.html
    - directives_ordering

    # Conditions should not unconditionally evaluate to `true` or to `false`.
    # http://dart-lang.github.io/linter/lints/invariant_booleans.html
    # reason: There are several outstanding bugs with this lint that cause a good deal of noise
    - invariant_booleans

    # Join return statement with assignment when possible.
    # http://dart-lang.github.io/linter/lints/join_return_with_assignment.html
    - join_return_with_assignment

    # Boolean expression composed only with literals.
    # http://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html
    - literal_only_boolean_expressions

    # Don't use adjacent strings in list.
    # http://dart-lang.github.io/linter/lints/no_adjacent_strings_in_list.html
    - no_adjacent_strings_in_list

    # Avoid defining a one-member abstract class when a simple function will do.
    # http://dart-lang.github.io/linter/lints/one_member_abstracts.html
    - one_member_abstracts

    # Only throw instances of classes extending either Exception or Error.
    # http://dart-lang.github.io/linter/lints/only_throw_errors.html
    - only_throw_errors

    # Provide doc comments for all public APIs.
    # http://dart-lang.github.io/linter/lints/package_api_docs.html
    - package_api_docs

    # Prefer putting asserts in initializer list.
    # http://dart-lang.github.io/linter/lints/prefer_asserts_in_initializer_lists.html
    - prefer_asserts_in_initializer_lists

    # Prefer const with constant constructors.
    # http://dart-lang.github.io/linter/lints/prefer_const_constructors.html
    - prefer_const_constructors

    # Prefer declare const constructors on `@immutable` classes.
    # http://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html
    - prefer_const_constructors_in_immutables

    # Prefer const over final for declarations.
    # http://dart-lang.github.io/linter/lints/prefer_const_declarations.html
    - prefer_const_declarations

    # Prefer const literals as parameters of constructors on @immutable classes.
    # http://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html
    - prefer_const_literals_to_create_immutables

    # Prefer defining constructors instead of static methods to create instances.
    # http://dart-lang.github.io/linter/lints/prefer_constructors_over_static_methods.html
    - prefer_constructors_over_static_methods

    # Prefer final in for-each loop variable if reference is not reassigned.
    # http://dart-lang.github.io/linter/lints/prefer_final_in_for_each.html
    - prefer_final_in_for_each

    # Use `forEach` to only apply a function to all the elements.
    # http://dart-lang.github.io/linter/lints/prefer_foreach.html
    - prefer_foreach

    # Prefer if elements to conditional expressions where possible.
    # http://dart-lang.github.io/linter/lints/prefer_if_elements_to_conditional_expressions.html
    - prefer_if_elements_to_conditional_expressions

    # Prefer int literals over double literals.
    # http://dart-lang.github.io/linter/lints/prefer_int_literals.html
    - prefer_int_literals

    # Prefer using mixins.
    # http://dart-lang.github.io/linter/lints/prefer_mixin.html
    - prefer_mixin

    # Sort child properties last in widget instance creations.
    # http://dart-lang.github.io/linter/lints/sort_child_properties_last.html
    - sort_child_properties_last

    # Sort pub dependencies.
    # http://dart-lang.github.io/linter/lints/sort_pub_dependencies.html
    - sort_pub_dependencies

    # Sort unnamed constructor declarations first.
    # http://dart-lang.github.io/linter/lints/sort_unnamed_constructors_first.html
    - sort_unnamed_constructors_first

    # Test type arguments in operator ==(Object other).
    # http://dart-lang.github.io/linter/lints/test_types_in_equals.html
    - test_types_in_equals

    # Avoid `throw` in finally block.
    # http://dart-lang.github.io/linter/lints/throw_in_finally.html
    - throw_in_finally

    # Type annotate public APIs.
    # http://dart-lang.github.io/linter/lints/type_annotate_public_apis.html
    # reason: React component render() method can return either ReactElement or false. Use overrides.
    - type_annotate_public_apis

    # Unnecessary await keyword in return.
    # http://dart-lang.github.io/linter/lints/unnecessary_await_in_return.html
    - unnecessary_await_in_return

    # Don't create a lambda when a tear-off will do.
    # http://dart-lang.github.io/linter/lints/unnecessary_lambdas.html
    - unnecessary_lambdas

    # Avoid null in null-aware assignment.
    # http://dart-lang.github.io/linter/lints/unnecessary_null_aware_assignments.html
    - unnecessary_null_aware_assignments

    # Unnecessary parenthesis can be removed.
    # http://dart-lang.github.io/linter/lints/unnecessary_parenthesis.html
    - unnecessary_parenthesis

    # Avoid using unnecessary statements.
    # http://dart-lang.github.io/linter/lints/unnecessary_statements.html
    - unnecessary_statements

    # Prefer an 8-digit hexadecimal integer(0xFFFFFFFF) to instantiate Color.
    # http://dart-lang.github.io/linter/lints/use_full_hex_values_for_flutter_colors.html
    - use_full_hex_values_for_flutter_colors

    # Use a setter for operations that conceptually change a property.
    # http://dart-lang.github.io/linter/lints/use_setters_to_change_properties.html
    - use_setters_to_change_properties

    # Use string buffers to compose strings.
    # http://dart-lang.github.io/linter/lints/use_string_buffers.html
    - use_string_buffers

    # Start the name of the method with to/_to or as/_as if applicable.
    # http://dart-lang.github.io/linter/lints/use_to_and_as_if_applicable.html
    - use_to_and_as_if_applicable

    - omit_local_variable_types
    - require_trailing_commas
    - prefer_expression_function_bodies
