// GENERATED CODE - DO NOT MODIFY BY HAND
// @dart=2.6

part of serializers;

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(ActionsBillingUsage.serializer)
      ..add(ActionsBillingUsageMinutesUsedBreakdown.serializer)
      ..add(ActionsEnterprisePermissions.serializer)
      ..add(ActionsOrganizationPermissions.serializer)
      ..add(ActionsPublicKey.serializer)
      ..add(ActionsRepositoryPermissions.serializer)
      ..add(ActionsSecret.serializer)
      ..add(Actor.serializer)
      ..add(AllowedActions.serializer)
      ..add(ApiOverview.serializer)
      ..add(ApiOverviewSshKeyFingerprints.serializer)
      ..add(AppPermissions.serializer)
      ..add(AppPermissionsActionsEnum.serializer)
      ..add(AppPermissionsAdministrationEnum.serializer)
      ..add(AppPermissionsChecksEnum.serializer)
      ..add(AppPermissionsContentReferencesEnum.serializer)
      ..add(AppPermissionsContentsEnum.serializer)
      ..add(AppPermissionsDeploymentsEnum.serializer)
      ..add(AppPermissionsEnvironmentsEnum.serializer)
      ..add(AppPermissionsIssuesEnum.serializer)
      ..add(AppPermissionsMembersEnum.serializer)
      ..add(AppPermissionsMetadataEnum.serializer)
      ..add(AppPermissionsOrganizationAdministrationEnum.serializer)
      ..add(AppPermissionsOrganizationHooksEnum.serializer)
      ..add(AppPermissionsOrganizationPlanEnum.serializer)
      ..add(AppPermissionsOrganizationProjectsEnum.serializer)
      ..add(AppPermissionsOrganizationSecretsEnum.serializer)
      ..add(AppPermissionsOrganizationSelfHostedRunnersEnum.serializer)
      ..add(AppPermissionsOrganizationUserBlockingEnum.serializer)
      ..add(AppPermissionsPackagesEnum.serializer)
      ..add(AppPermissionsPagesEnum.serializer)
      ..add(AppPermissionsPullRequestsEnum.serializer)
      ..add(AppPermissionsRepositoryHooksEnum.serializer)
      ..add(AppPermissionsRepositoryProjectsEnum.serializer)
      ..add(AppPermissionsSecretScanningAlertsEnum.serializer)
      ..add(AppPermissionsSecretsEnum.serializer)
      ..add(AppPermissionsSecurityEventsEnum.serializer)
      ..add(AppPermissionsSingleFileEnum.serializer)
      ..add(AppPermissionsStatusesEnum.serializer)
      ..add(AppPermissionsTeamDiscussionsEnum.serializer)
      ..add(AppPermissionsVulnerabilityAlertsEnum.serializer)
      ..add(AppPermissionsWorkflowsEnum.serializer)
      ..add(ApplicationGrant.serializer)
      ..add(ApplicationGrantApp.serializer)
      ..add(Artifact.serializer)
      ..add(AuditLogEvent.serializer)
      ..add(AuthenticationToken.serializer)
      ..add(AuthenticationTokenRepositorySelectionEnum.serializer)
      ..add(AuthorAssociation.serializer)
      ..add(Authorization.serializer)
      ..add(AutoMerge.serializer)
      ..add(AutoMergeMergeMethodEnum.serializer)
      ..add(BaseGist.serializer)
      ..add(BaseGistFiles.serializer)
      ..add(BasicError.serializer)
      ..add(Blob.serializer)
      ..add(BranchProtection.serializer)
      ..add(BranchProtectionRequiredLinearHistory.serializer)
      ..add(BranchProtectionRequiredStatusChecks.serializer)
      ..add(BranchRestrictionPolicy.serializer)
      ..add(BranchRestrictionPolicyApps.serializer)
      ..add(BranchRestrictionPolicyOwner.serializer)
      ..add(BranchRestrictionPolicyPermissions.serializer)
      ..add(BranchRestrictionPolicyTeams.serializer)
      ..add(BranchShort.serializer)
      ..add(BranchShortCommit.serializer)
      ..add(BranchWithProtection.serializer)
      ..add(BranchWithProtectionLinks.serializer)
      ..add(CheckAnnotation.serializer)
      ..add(CheckRun.serializer)
      ..add(CheckRunCheckSuite.serializer)
      ..add(CheckRunConclusionEnum.serializer)
      ..add(CheckRunOutput.serializer)
      ..add(CheckRunStatusEnum.serializer)
      ..add(CheckSuite.serializer)
      ..add(CheckSuiteConclusionEnum.serializer)
      ..add(CheckSuitePreference.serializer)
      ..add(CheckSuitePreferencePreferences.serializer)
      ..add(CheckSuitePreferencePreferencesAutoTriggerChecks.serializer)
      ..add(CheckSuiteStatusEnum.serializer)
      ..add(CloneTraffic.serializer)
      ..add(CodeOfConduct.serializer)
      ..add(CodeOfConductSimple.serializer)
      ..add(CodeScanningAlert.serializer)
      ..add(CodeScanningAlertClassification.serializer)
      ..add(CodeScanningAlertDismissedReason.serializer)
      ..add(CodeScanningAlertDismissedReasonOneOf.serializer)
      ..add(CodeScanningAlertDismissedReasonOneOf1.serializer)
      ..add(CodeScanningAlertInstance.serializer)
      ..add(CodeScanningAlertInstanceMessage.serializer)
      ..add(CodeScanningAlertItems.serializer)
      ..add(CodeScanningAlertLocation.serializer)
      ..add(CodeScanningAlertRule.serializer)
      ..add(CodeScanningAlertRuleSeverityEnum.serializer)
      ..add(CodeScanningAlertRuleSummary.serializer)
      ..add(CodeScanningAlertRuleSummarySeverityEnum.serializer)
      ..add(CodeScanningAlertSetState.serializer)
      ..add(CodeScanningAlertState.serializer)
      ..add(CodeScanningAnalysis.serializer)
      ..add(CodeScanningAnalysisDeletion.serializer)
      ..add(CodeScanningAnalysisTool.serializer)
      ..add(CodeScanningSarifsReceipt.serializer)
      ..add(CodeScanningSarifsStatus.serializer)
      ..add(CodeScanningSarifsStatusProcessingStatusEnum.serializer)
      ..add(CodeSearchResultItem.serializer)
      ..add(Collaborator.serializer)
      ..add(CollaboratorPermissions.serializer)
      ..add(CombinedBillingUsage.serializer)
      ..add(CombinedCommitStatus.serializer)
      ..add(Commit.serializer)
      ..add(CommitActivity.serializer)
      ..add(CommitComment.serializer)
      ..add(CommitCommit.serializer)
      ..add(CommitCommitTree.serializer)
      ..add(CommitComparison.serializer)
      ..add(CommitComparisonStatusEnum.serializer)
      ..add(CommitFiles.serializer)
      ..add(CommitParents.serializer)
      ..add(CommitSearchResultItem.serializer)
      ..add(CommitSearchResultItemCommit.serializer)
      ..add(CommitSearchResultItemCommitAuthor.serializer)
      ..add(CommitStats.serializer)
      ..add(CommunityHealthFile.serializer)
      ..add(CommunityProfile.serializer)
      ..add(CommunityProfileFiles.serializer)
      ..add(ContainerMetadata.serializer)
      ..add(ContentFile.serializer)
      ..add(ContentReferenceAttachment.serializer)
      ..add(ContentSubmodule.serializer)
      ..add(ContentSymlink.serializer)
      ..add(ContentTraffic.serializer)
      ..add(ContentTree.serializer)
      ..add(ContentTreeEntries.serializer)
      ..add(ContentTreeLinks.serializer)
      ..add(Contributor.serializer)
      ..add(ContributorActivity.serializer)
      ..add(ContributorActivityWeeks.serializer)
      ..add(CredentialAuthorization.serializer)
      ..add(DeployKey.serializer)
      ..add(Deployment.serializer)
      ..add(DeploymentBranchPolicy.serializer)
      ..add(DeploymentReviewerType.serializer)
      ..add(DeploymentSimple.serializer)
      ..add(DeploymentStatus.serializer)
      ..add(DeploymentStatusStateEnum.serializer)
      ..add(DiffEntry.serializer)
      ..add(DockerMetadata.serializer)
      ..add(Email.serializer)
      ..add(EnabledOrganizations.serializer)
      ..add(EnabledRepositories.serializer)
      ..add(Enterprise.serializer)
      ..add(Environment.serializer)
      ..add(EnvironmentApprovals.serializer)
      ..add(EnvironmentApprovalsEnvironments.serializer)
      ..add(EnvironmentApprovalsStateEnum.serializer)
      ..add(Event.serializer)
      ..add(EventPayload.serializer)
      ..add(EventPayloadPages.serializer)
      ..add(EventRepo.serializer)
      ..add(Feed.serializer)
      ..add(FeedLinks.serializer)
      ..add(FileCommit.serializer)
      ..add(FileCommitCommit.serializer)
      ..add(FileCommitCommitAuthor.serializer)
      ..add(FileCommitCommitParents.serializer)
      ..add(FileCommitCommitTree.serializer)
      ..add(FileCommitCommitVerification.serializer)
      ..add(FileCommitContent.serializer)
      ..add(FileCommitContentLinks.serializer)
      ..add(FullRepository.serializer)
      ..add(FullRepositoryPermissions.serializer)
      ..add(GistComment.serializer)
      ..add(GistCommit.serializer)
      ..add(GistCommitChangeStatus.serializer)
      ..add(GistSimple.serializer)
      ..add(GistSimpleFiles.serializer)
      ..add(GistsFiles.serializer)
      ..add(GitCommit.serializer)
      ..add(GitCommitAuthor.serializer)
      ..add(GitCommitParents.serializer)
      ..add(GitCommitTree.serializer)
      ..add(GitCommitVerification.serializer)
      ..add(GitRef.serializer)
      ..add(GitRefObject.serializer)
      ..add(GitTag.serializer)
      ..add(GitTagObject.serializer)
      ..add(GitTagTagger.serializer)
      ..add(GitTree.serializer)
      ..add(GitTreeTree.serializer)
      ..add(GitUser.serializer)
      ..add(GitignoreTemplate.serializer)
      ..add(GpgKey.serializer)
      ..add(GpgKeyEmails.serializer)
      ..add(GpgKeySubkeys.serializer)
      ..add(GroupMapping.serializer)
      ..add(GroupMappingGroups.serializer)
      ..add(Hook.serializer)
      ..add(HookConfig.serializer)
      ..add(HookResponse.serializer)
      ..add(Hovercard.serializer)
      ..add(HovercardContexts.serializer)
      ..add(ImportProjectChoices.serializer)
      ..add(InlineObject.serializer)
      ..add(InlineObject1.serializer)
      ..add(InlineObject10.serializer)
      ..add(InlineObject100.serializer)
      ..add(InlineObject100TypeEnum.serializer)
      ..add(InlineObject101.serializer)
      ..add(InlineObject102.serializer)
      ..add(InlineObject103.serializer)
      ..add(InlineObject104.serializer)
      ..add(InlineObject105.serializer)
      ..add(InlineObject105VcsEnum.serializer)
      ..add(InlineObject106.serializer)
      ..add(InlineObject107.serializer)
      ..add(InlineObject108.serializer)
      ..add(InlineObject108UseLfsEnum.serializer)
      ..add(InlineObject109.serializer)
      ..add(InlineObject109PermissionsEnum.serializer)
      ..add(InlineObject11.serializer)
      ..add(InlineObject110.serializer)
      ..add(InlineObject111.serializer)
      ..add(InlineObject112.serializer)
      ..add(InlineObject112ContentEnum.serializer)
      ..add(InlineObject113.serializer)
      ..add(InlineObject113StateEnum.serializer)
      ..add(InlineObject114.serializer)
      ..add(InlineObject115.serializer)
      ..add(InlineObject116.serializer)
      ..add(InlineObject117.serializer)
      ..add(InlineObject118.serializer)
      ..add(InlineObject119.serializer)
      ..add(InlineObject119LockReasonEnum.serializer)
      ..add(InlineObject12.serializer)
      ..add(InlineObject120.serializer)
      ..add(InlineObject120ContentEnum.serializer)
      ..add(InlineObject121.serializer)
      ..add(InlineObject122.serializer)
      ..add(InlineObject123.serializer)
      ..add(InlineObject124.serializer)
      ..add(InlineObject125.serializer)
      ..add(InlineObject125StateEnum.serializer)
      ..add(InlineObject126.serializer)
      ..add(InlineObject126StateEnum.serializer)
      ..add(InlineObject127.serializer)
      ..add(InlineObject128.serializer)
      ..add(InlineObject129.serializer)
      ..add(InlineObject13.serializer)
      ..add(InlineObject130.serializer)
      ..add(InlineObject131.serializer)
      ..add(InlineObject132.serializer)
      ..add(InlineObject133.serializer)
      ..add(InlineObject133ContentEnum.serializer)
      ..add(InlineObject134.serializer)
      ..add(InlineObject134StateEnum.serializer)
      ..add(InlineObject135.serializer)
      ..add(InlineObject135SideEnum.serializer)
      ..add(InlineObject135StartSideEnum.serializer)
      ..add(InlineObject136.serializer)
      ..add(InlineObject137.serializer)
      ..add(InlineObject137MergeMethodEnum.serializer)
      ..add(InlineObject138.serializer)
      ..add(InlineObject139.serializer)
      ..add(InlineObject139EventEnum.serializer)
      ..add(InlineObject14.serializer)
      ..add(InlineObject140.serializer)
      ..add(InlineObject141.serializer)
      ..add(InlineObject142.serializer)
      ..add(InlineObject142EventEnum.serializer)
      ..add(InlineObject143.serializer)
      ..add(InlineObject144.serializer)
      ..add(InlineObject145.serializer)
      ..add(InlineObject146.serializer)
      ..add(InlineObject147.serializer)
      ..add(InlineObject148.serializer)
      ..add(InlineObject148StateEnum.serializer)
      ..add(InlineObject149.serializer)
      ..add(InlineObject14VisibilityEnum.serializer)
      ..add(InlineObject15.serializer)
      ..add(InlineObject150.serializer)
      ..add(InlineObject151.serializer)
      ..add(InlineObject152.serializer)
      ..add(InlineObject153.serializer)
      ..add(InlineObject154.serializer)
      ..add(InlineObject155.serializer)
      ..add(InlineObject156.serializer)
      ..add(InlineObject157.serializer)
      ..add(InlineObject158.serializer)
      ..add(InlineObject159.serializer)
      ..add(InlineObject15VisibilityEnum.serializer)
      ..add(InlineObject16.serializer)
      ..add(InlineObject160.serializer)
      ..add(InlineObject161.serializer)
      ..add(InlineObject162.serializer)
      ..add(InlineObject163.serializer)
      ..add(InlineObject163PermissionEnum.serializer)
      ..add(InlineObject163PrivacyEnum.serializer)
      ..add(InlineObject164.serializer)
      ..add(InlineObject165.serializer)
      ..add(InlineObject166.serializer)
      ..add(InlineObject167.serializer)
      ..add(InlineObject168.serializer)
      ..add(InlineObject168ContentEnum.serializer)
      ..add(InlineObject169.serializer)
      ..add(InlineObject169ContentEnum.serializer)
      ..add(InlineObject17.serializer)
      ..add(InlineObject170.serializer)
      ..add(InlineObject170RoleEnum.serializer)
      ..add(InlineObject171.serializer)
      ..add(InlineObject171PermissionEnum.serializer)
      ..add(InlineObject172.serializer)
      ..add(InlineObject172PermissionEnum.serializer)
      ..add(InlineObject173.serializer)
      ..add(InlineObject174.serializer)
      ..add(InlineObject175.serializer)
      ..add(InlineObject175VisibilityEnum.serializer)
      ..add(InlineObject176.serializer)
      ..add(InlineObject177.serializer)
      ..add(InlineObject178.serializer)
      ..add(InlineObject178StateEnum.serializer)
      ..add(InlineObject179.serializer)
      ..add(InlineObject179ExcludeEnum.serializer)
      ..add(InlineObject18.serializer)
      ..add(InlineObject180.serializer)
      ..add(InlineObject181.serializer)
      ..add(InlineObject19.serializer)
      ..add(InlineObject2.serializer)
      ..add(InlineObject20.serializer)
      ..add(InlineObject21.serializer)
      ..add(InlineObject21ModeEnum.serializer)
      ..add(InlineObject22.serializer)
      ..add(InlineObject23.serializer)
      ..add(InlineObject24.serializer)
      ..add(InlineObject24DefaultRepositoryPermissionEnum.serializer)
      ..add(InlineObject24MembersAllowedRepositoryCreationTypeEnum.serializer)
      ..add(InlineObject25.serializer)
      ..add(InlineObject26.serializer)
      ..add(InlineObject27.serializer)
      ..add(InlineObject27VisibilityEnum.serializer)
      ..add(InlineObject28.serializer)
      ..add(InlineObject28VisibilityEnum.serializer)
      ..add(InlineObject29.serializer)
      ..add(InlineObject3.serializer)
      ..add(InlineObject30.serializer)
      ..add(InlineObject31.serializer)
      ..add(InlineObject31VisibilityEnum.serializer)
      ..add(InlineObject32.serializer)
      ..add(InlineObject33.serializer)
      ..add(InlineObject34.serializer)
      ..add(InlineObject35.serializer)
      ..add(InlineObject36.serializer)
      ..add(InlineObject36RoleEnum.serializer)
      ..add(InlineObject37.serializer)
      ..add(InlineObject37RoleEnum.serializer)
      ..add(InlineObject38.serializer)
      ..add(InlineObject39.serializer)
      ..add(InlineObject4.serializer)
      ..add(InlineObject40.serializer)
      ..add(InlineObject40VisibilityEnum.serializer)
      ..add(InlineObject41.serializer)
      ..add(InlineObject41PermissionEnum.serializer)
      ..add(InlineObject41PrivacyEnum.serializer)
      ..add(InlineObject42.serializer)
      ..add(InlineObject42PermissionEnum.serializer)
      ..add(InlineObject42PrivacyEnum.serializer)
      ..add(InlineObject43.serializer)
      ..add(InlineObject44.serializer)
      ..add(InlineObject45.serializer)
      ..add(InlineObject46.serializer)
      ..add(InlineObject47.serializer)
      ..add(InlineObject47ContentEnum.serializer)
      ..add(InlineObject48.serializer)
      ..add(InlineObject48ContentEnum.serializer)
      ..add(InlineObject49.serializer)
      ..add(InlineObject49RoleEnum.serializer)
      ..add(InlineObject5.serializer)
      ..add(InlineObject50.serializer)
      ..add(InlineObject50PermissionEnum.serializer)
      ..add(InlineObject51.serializer)
      ..add(InlineObject51PermissionEnum.serializer)
      ..add(InlineObject52.serializer)
      ..add(InlineObject53.serializer)
      ..add(InlineObject54.serializer)
      ..add(InlineObject55.serializer)
      ..add(InlineObject56.serializer)
      ..add(InlineObject57.serializer)
      ..add(InlineObject57OrganizationPermissionEnum.serializer)
      ..add(InlineObject58.serializer)
      ..add(InlineObject58PermissionEnum.serializer)
      ..add(InlineObject59.serializer)
      ..add(InlineObject6.serializer)
      ..add(InlineObject60.serializer)
      ..add(InlineObject60VisibilityEnum.serializer)
      ..add(InlineObject61.serializer)
      ..add(InlineObject62.serializer)
      ..add(InlineObject62StateEnum.serializer)
      ..add(InlineObject63.serializer)
      ..add(InlineObject64.serializer)
      ..add(InlineObject65.serializer)
      ..add(InlineObject66.serializer)
      ..add(InlineObject67.serializer)
      ..add(InlineObject68.serializer)
      ..add(InlineObject69.serializer)
      ..add(InlineObject7.serializer)
      ..add(InlineObject70.serializer)
      ..add(InlineObject71.serializer)
      ..add(InlineObject72.serializer)
      ..add(InlineObject73.serializer)
      ..add(InlineObject74.serializer)
      ..add(InlineObject75.serializer)
      ..add(InlineObject76.serializer)
      ..add(InlineObject77.serializer)
      ..add(InlineObject78.serializer)
      ..add(InlineObject79.serializer)
      ..add(InlineObject8.serializer)
      ..add(InlineObject80.serializer)
      ..add(InlineObject81.serializer)
      ..add(InlineObject82.serializer)
      ..add(InlineObject83.serializer)
      ..add(InlineObject84.serializer)
      ..add(InlineObject85.serializer)
      ..add(InlineObject85PermissionEnum.serializer)
      ..add(InlineObject86.serializer)
      ..add(InlineObject87.serializer)
      ..add(InlineObject87ContentEnum.serializer)
      ..add(InlineObject88.serializer)
      ..add(InlineObject89.serializer)
      ..add(InlineObject9.serializer)
      ..add(InlineObject90.serializer)
      ..add(InlineObject91.serializer)
      ..add(InlineObject92.serializer)
      ..add(InlineObject92EnvironmentEnum.serializer)
      ..add(InlineObject92StateEnum.serializer)
      ..add(InlineObject93.serializer)
      ..add(InlineObject94.serializer)
      ..add(InlineObject95.serializer)
      ..add(InlineObject96.serializer)
      ..add(InlineObject97.serializer)
      ..add(InlineObject98.serializer)
      ..add(InlineObject99.serializer)
      ..add(InlineResponse200.serializer)
      ..add(InlineResponse2001.serializer)
      ..add(InlineResponse20010.serializer)
      ..add(InlineResponse20011.serializer)
      ..add(InlineResponse20012.serializer)
      ..add(InlineResponse20013.serializer)
      ..add(InlineResponse20014.serializer)
      ..add(InlineResponse20015.serializer)
      ..add(InlineResponse20016.serializer)
      ..add(InlineResponse20017.serializer)
      ..add(InlineResponse20018.serializer)
      ..add(InlineResponse20019.serializer)
      ..add(InlineResponse2002.serializer)
      ..add(InlineResponse20020.serializer)
      ..add(InlineResponse20021.serializer)
      ..add(InlineResponse20022.serializer)
      ..add(InlineResponse20023.serializer)
      ..add(InlineResponse20024.serializer)
      ..add(InlineResponse20025.serializer)
      ..add(InlineResponse20026.serializer)
      ..add(InlineResponse20027.serializer)
      ..add(InlineResponse2003.serializer)
      ..add(InlineResponse2004.serializer)
      ..add(InlineResponse2005.serializer)
      ..add(InlineResponse2006.serializer)
      ..add(InlineResponse2007.serializer)
      ..add(InlineResponse2008.serializer)
      ..add(InlineResponse2009.serializer)
      ..add(InlineResponse202.serializer)
      ..add(InlineResponse2021.serializer)
      ..add(InlineResponse403.serializer)
      ..add(InlineResponse4031.serializer)
      ..add(InlineResponse4032.serializer)
      ..add(InlineResponse4033.serializer)
      ..add(InlineResponse4033Errors.serializer)
      ..add(InlineResponse403Block.serializer)
      ..add(InlineResponse404.serializer)
      ..add(InlineResponse409.serializer)
      ..add(InlineResponse415.serializer)
      ..add(InlineResponse422.serializer)
      ..add(InlineResponse4221.serializer)
      ..add(InlineResponse4222.serializer)
      ..add(InlineResponse422Errors.serializer)
      ..add(InlineResponse503.serializer)
      ..add(InlineResponse5031.serializer)
      ..add(InlineResponse5031Errors.serializer)
      ..add(Installation.serializer)
      ..add(InstallationPermissions.serializer)
      ..add(InstallationRepositorySelectionEnum.serializer)
      ..add(InstallationToken.serializer)
      ..add(InstallationTokenPermissions.serializer)
      ..add(InstallationTokenRepositorySelectionEnum.serializer)
      ..add(Integration.serializer)
      ..add(InteractionExpiry.serializer)
      ..add(InteractionGroup.serializer)
      ..add(InteractionLimit.serializer)
      ..add(InteractionLimitResponse.serializer)
      ..add(Issue.serializer)
      ..add(IssueComment.serializer)
      ..add(IssueEvent.serializer)
      ..add(IssueEventDismissedReview.serializer)
      ..add(IssueEventForIssue.serializer)
      ..add(IssueEventLabel.serializer)
      ..add(IssueEventMilestone.serializer)
      ..add(IssueEventProjectCard.serializer)
      ..add(IssueEventRename.serializer)
      ..add(IssueSearchResultItem.serializer)
      ..add(IssueSearchResultItemLabels.serializer)
      ..add(IssueSimple.serializer)
      ..add(IssueSimplePullRequest.serializer)
      ..add(Job.serializer)
      ..add(JobStatusEnum.serializer)
      ..add(JobSteps.serializer)
      ..add(JobStepsStatusEnum.serializer)
      ..add(Key.serializer)
      ..add(KeySimple.serializer)
      ..add(Label.serializer)
      ..add(LabelSearchResultItem.serializer)
      ..add(License.serializer)
      ..add(LicenseContent.serializer)
      ..add(LicenseSimple.serializer)
      ..add(Link.serializer)
      ..add(LinkWithType.serializer)
      ..add(MarketplaceAccount.serializer)
      ..add(MarketplaceListingPlan.serializer)
      ..add(MarketplacePurchase.serializer)
      ..add(MarketplacePurchaseMarketplacePendingChange.serializer)
      ..add(MarketplacePurchaseMarketplacePurchase.serializer)
      ..add(Migration.serializer)
      ..add(Milestone.serializer)
      ..add(MilestoneStateEnum.serializer)
      ..add(MinimalRepository.serializer)
      ..add(MinimalRepositoryLicense.serializer)
      ..add(ModelImport.serializer)
      ..add(ModelImportStatusEnum.serializer)
      ..add(OrgHook.serializer)
      ..add(OrgHookConfig.serializer)
      ..add(OrgMembership.serializer)
      ..add(OrgMembershipPermissions.serializer)
      ..add(OrganizationActionsSecret.serializer)
      ..add(OrganizationActionsSecretVisibilityEnum.serializer)
      ..add(OrganizationFull.serializer)
      ..add(OrganizationFullPlan.serializer)
      ..add(OrganizationInvitation.serializer)
      ..add(OrganizationSimple.serializer)
      ..add(OrgsOrgHooksConfig.serializer)
      ..add(OrgsOrgHooksHookIdConfig.serializer)
      ..add(OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups.serializer)
      ..add(Package.serializer)
      ..add(PackagePackageTypeEnum.serializer)
      ..add(PackageVersion.serializer)
      ..add(PackageVersionMetadata.serializer)
      ..add(PackageVersionMetadataPackageTypeEnum.serializer)
      ..add(PackageVisibilityEnum.serializer)
      ..add(PackagesBillingUsage.serializer)
      ..add(Page.serializer)
      ..add(PageBuild.serializer)
      ..add(PageBuildError.serializer)
      ..add(PageBuildStatus.serializer)
      ..add(PageStatusEnum.serializer)
      ..add(PagesSourceHash.serializer)
      ..add(ParticipationStats.serializer)
      ..add(PendingDeployment.serializer)
      ..add(PendingDeploymentEnvironment.serializer)
      ..add(PendingDeploymentReviewers.serializer)
      ..add(PorterAuthor.serializer)
      ..add(PorterLargeFile.serializer)
      ..add(PrivateUser.serializer)
      ..add(PrivateUserPlan.serializer)
      ..add(Project.serializer)
      ..add(ProjectCard.serializer)
      ..add(ProjectColumn.serializer)
      ..add(ProjectOrganizationPermissionEnum.serializer)
      ..add(ProtectedBranch.serializer)
      ..add(ProtectedBranchAdminEnforced.serializer)
      ..add(ProtectedBranchEnforceAdmins.serializer)
      ..add(ProtectedBranchPullRequestReview.serializer)
      ..add(ProtectedBranchPullRequestReviewDismissalRestrictions.serializer)
      ..add(ProtectedBranchRequiredLinearHistory.serializer)
      ..add(ProtectedBranchRequiredPullRequestReviews.serializer)
      ..add(ProtectedBranchRequiredPullRequestReviewsDismissalRestrictions
          .serializer)
      ..add(ProtectedBranchRequiredSignatures.serializer)
      ..add(PublicUser.serializer)
      ..add(PullRequest.serializer)
      ..add(PullRequestBase.serializer)
      ..add(PullRequestBaseRepo.serializer)
      ..add(PullRequestHead.serializer)
      ..add(PullRequestHeadRepo.serializer)
      ..add(PullRequestHeadRepoLicense.serializer)
      ..add(PullRequestHeadRepoOwner.serializer)
      ..add(PullRequestLabels.serializer)
      ..add(PullRequestMergeResult.serializer)
      ..add(PullRequestMinimal.serializer)
      ..add(PullRequestMinimalHead.serializer)
      ..add(PullRequestMinimalHeadRepo.serializer)
      ..add(PullRequestReview.serializer)
      ..add(PullRequestReviewComment.serializer)
      ..add(PullRequestReviewCommentLinks.serializer)
      ..add(PullRequestReviewCommentLinksHtml.serializer)
      ..add(PullRequestReviewCommentLinksPullRequest.serializer)
      ..add(PullRequestReviewCommentLinksSelf.serializer)
      ..add(PullRequestReviewCommentSideEnum.serializer)
      ..add(PullRequestReviewCommentStartSideEnum.serializer)
      ..add(PullRequestReviewLinks.serializer)
      ..add(PullRequestReviewLinksHtml.serializer)
      ..add(PullRequestReviewRequest.serializer)
      ..add(PullRequestSimple.serializer)
      ..add(PullRequestSimpleHead.serializer)
      ..add(PullRequestSimpleLabels.serializer)
      ..add(PullRequestSimpleLinks.serializer)
      ..add(PullRequestStateEnum.serializer)
      ..add(RateLimit.serializer)
      ..add(RateLimitOverview.serializer)
      ..add(RateLimitOverviewResources.serializer)
      ..add(Reaction.serializer)
      ..add(ReactionContentEnum.serializer)
      ..add(ReactionRollup.serializer)
      ..add(ReferrerTraffic.serializer)
      ..add(Release.serializer)
      ..add(ReleaseAsset.serializer)
      ..add(ReleaseAssetStateEnum.serializer)
      ..add(RepoSearchResultItem.serializer)
      ..add(ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews
          .serializer)
      ..add(ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions
          .serializer)
      ..add(
          ReposOwnerRepoBranchesBranchProtectionRequiredStatusChecks.serializer)
      ..add(ReposOwnerRepoBranchesBranchProtectionRestrictions.serializer)
      ..add(ReposOwnerRepoCheckSuitesPreferencesAutoTriggerChecks.serializer)
      ..add(ReposOwnerRepoContentsPathAuthor.serializer)
      ..add(ReposOwnerRepoContentsPathAuthor1.serializer)
      ..add(ReposOwnerRepoContentsPathCommitter.serializer)
      ..add(ReposOwnerRepoContentsPathCommitter1.serializer)
      ..add(ReposOwnerRepoEnvironmentsEnvironmentNameReviewers.serializer)
      ..add(ReposOwnerRepoGitCommitsAuthor.serializer)
      ..add(ReposOwnerRepoGitCommitsCommitter.serializer)
      ..add(ReposOwnerRepoGitTagsTagger.serializer)
      ..add(ReposOwnerRepoGitTreesTree.serializer)
      ..add(ReposOwnerRepoGitTreesTreeModeEnum.serializer)
      ..add(ReposOwnerRepoGitTreesTreeTypeEnum.serializer)
      ..add(ReposOwnerRepoHooksConfig.serializer)
      ..add(ReposOwnerRepoHooksHookIdConfig.serializer)
      ..add(ReposOwnerRepoPagesSource.serializer)
      ..add(ReposOwnerRepoPagesSourcePathEnum.serializer)
      ..add(ReposOwnerRepoPullsPullNumberReviewsComments.serializer)
      ..add(Repository.serializer)
      ..add(RepositoryCollaboratorPermission.serializer)
      ..add(RepositoryInvitation.serializer)
      ..add(RepositoryInvitationPermissionsEnum.serializer)
      ..add(RepositoryPermissions.serializer)
      ..add(RepositorySubscription.serializer)
      ..add(RepositoryTemplateRepository.serializer)
      ..add(RepositoryTemplateRepositoryOwner.serializer)
      ..add(RepositoryTemplateRepositoryPermissions.serializer)
      ..add(ReviewComment.serializer)
      ..add(ReviewCommentLinks.serializer)
      ..add(ReviewCommentSideEnum.serializer)
      ..add(ReviewCommentStartSideEnum.serializer)
      ..add(Runner.serializer)
      ..add(RunnerApplication.serializer)
      ..add(RunnerGroupsEnterprise.serializer)
      ..add(RunnerGroupsOrg.serializer)
      ..add(RunnerLabels.serializer)
      ..add(RunnerLabelsTypeEnum.serializer)
      ..add(ScimEnterpriseGroup.serializer)
      ..add(ScimEnterpriseUser.serializer)
      ..add(ScimEnterpriseUserEmails.serializer)
      ..add(ScimError.serializer)
      ..add(ScimGroupListEnterprise.serializer)
      ..add(ScimGroupListEnterpriseMembers.serializer)
      ..add(ScimGroupListEnterpriseMeta.serializer)
      ..add(ScimGroupListEnterpriseResources.serializer)
      ..add(ScimUser.serializer)
      ..add(ScimUserEmails.serializer)
      ..add(ScimUserList.serializer)
      ..add(ScimUserListEnterprise.serializer)
      ..add(ScimUserListEnterpriseEmails.serializer)
      ..add(ScimUserListEnterpriseName.serializer)
      ..add(ScimUserListEnterpriseResources.serializer)
      ..add(ScimUserMeta.serializer)
      ..add(ScimUserName.serializer)
      ..add(ScimUserOperations.serializer)
      ..add(ScimUserOperationsOpEnum.serializer)
      ..add(ScimV2EnterprisesEnterpriseGroupsMembers.serializer)
      ..add(ScimV2EnterprisesEnterpriseUsersEmails.serializer)
      ..add(ScimV2EnterprisesEnterpriseUsersGroups.serializer)
      ..add(ScimV2EnterprisesEnterpriseUsersName.serializer)
      ..add(ScimV2OrganizationsOrgUsersEmails.serializer)
      ..add(ScimV2OrganizationsOrgUsersName.serializer)
      ..add(ScimV2OrganizationsOrgUsersScimUserIdEmails.serializer)
      ..add(ScimV2OrganizationsOrgUsersScimUserIdOperations.serializer)
      ..add(ScimV2OrganizationsOrgUsersScimUserIdOperationsOpEnum.serializer)
      ..add(ScopedInstallation.serializer)
      ..add(ScopedInstallationRepositorySelectionEnum.serializer)
      ..add(SecretScanningAlert.serializer)
      ..add(SecretScanningAlertResolution.serializer)
      ..add(SecretScanningAlertResolutionOneOf.serializer)
      ..add(SecretScanningAlertState.serializer)
      ..add(SelectedActions.serializer)
      ..add(ShortBlob.serializer)
      ..add(ShortBranch.serializer)
      ..add(ShortBranchCommit.serializer)
      ..add(SimpleCommit.serializer)
      ..add(SimpleCommitAuthor.serializer)
      ..add(SimpleCommitStatus.serializer)
      ..add(SimpleUser.serializer)
      ..add(Stargazer.serializer)
      ..add(StarredRepository.serializer)
      ..add(Status.serializer)
      ..add(StatusCheckPolicy.serializer)
      ..add(Tag.serializer)
      ..add(Team.serializer)
      ..add(TeamDiscussion.serializer)
      ..add(TeamDiscussionComment.serializer)
      ..add(TeamFull.serializer)
      ..add(TeamFullPrivacyEnum.serializer)
      ..add(TeamMembership.serializer)
      ..add(TeamMembershipRoleEnum.serializer)
      ..add(TeamProject.serializer)
      ..add(TeamProjectPermissions.serializer)
      ..add(TeamRepository.serializer)
      ..add(TeamSimple.serializer)
      ..add(TeamsTeamIdTeamSyncGroupMappingsGroups.serializer)
      ..add(Thread.serializer)
      ..add(ThreadSubject.serializer)
      ..add(ThreadSubscription.serializer)
      ..add(Topic.serializer)
      ..add(TopicSearchResultItem.serializer)
      ..add(TopicSearchResultItemRelated.serializer)
      ..add(TopicSearchResultItemTopicRelation.serializer)
      ..add(Traffic.serializer)
      ..add(UserMarketplacePurchase.serializer)
      ..add(UserSearchResultItem.serializer)
      ..add(ValidationError.serializer)
      ..add(ValidationErrorErrors.serializer)
      ..add(ValidationErrorSimple.serializer)
      ..add(Verification.serializer)
      ..add(ViewTraffic.serializer)
      ..add(WebhookConfig.serializer)
      ..add(Workflow.serializer)
      ..add(WorkflowRun.serializer)
      ..add(WorkflowRunUsage.serializer)
      ..add(WorkflowRunUsageBillable.serializer)
      ..add(WorkflowRunUsageBillableUBUNTU.serializer)
      ..add(WorkflowStateEnum.serializer)
      ..add(WorkflowUsage.serializer)
      ..add(WorkflowUsageBillable.serializer)
      ..add(WorkflowUsageBillableUBUNTU.serializer)
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(ActionsSecret)]),
          () => new ListBuilder<ActionsSecret>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Artifact)]),
          () => new ListBuilder<Artifact>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(CheckRun)]),
          () => new ListBuilder<CheckRun>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(CheckSuite)]),
          () => new ListBuilder<CheckSuite>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [
            const FullType(CheckSuitePreferencePreferencesAutoTriggerChecks)
          ]),
          () => new ListBuilder<
              CheckSuitePreferencePreferencesAutoTriggerChecks>())
      ..addBuilderFactory(
          const FullType(BuiltList,
              const [const FullType(CodeScanningAlertClassification)]),
          () => new ListBuilder<CodeScanningAlertClassification>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(CodeSearchResultItem)]),
          () => new ListBuilder<CodeSearchResultItem>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Commit)]),
          () => new ListBuilder<Commit>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(DiffEntry)]),
          () => new ListBuilder<DiffEntry>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(CommitParents)]),
          () => new ListBuilder<CommitParents>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(CommitFiles)]),
          () => new ListBuilder<CommitFiles>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(CommitSearchResultItem)]),
          () => new ListBuilder<CommitSearchResultItem>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(ContentTreeEntries)]),
          () => new ListBuilder<ContentTreeEntries>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(ContributorActivityWeeks)]),
          () => new ListBuilder<ContributorActivityWeeks>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(Environment)]),
          () => new ListBuilder<Environment>())
      ..addBuilderFactory(
          const FullType(BuiltList,
              const [const FullType(EnvironmentApprovalsEnvironments)]),
          () => new ListBuilder<EnvironmentApprovalsEnvironments>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(EventPayloadPages)]),
          () => new ListBuilder<EventPayloadPages>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(FileCommitCommitParents)]),
          () => new ListBuilder<FileCommitCommitParents>())
      ..addBuilderFactory(
          const FullType(
              BuiltList, const [const FullType(FileCommitCommitParents)]),
          () => new ListBuilder<FileCommitCommitParents>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(JsonObject)]),
          () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(GitCommitParents)]),
          () => new ListBuilder<GitCommitParents>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(GitTreeTree)]),
          () => new ListBuilder<GitTreeTree>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(GpgKeyEmails)]),
          () => new ListBuilder<GpgKeyEmails>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(GpgKeySubkeys)]),
          () => new ListBuilder<GpgKeySubkeys>())
      ..addBuilderFactory(
          const FullType(BuiltList, const [const FullType(GroupMappingGroups)]),
          () => new ListBuilder<GroupMappingGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(HovercardContexts)]), () => new ListBuilder<HovercardContexts>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ImportProjectChoices)]), () => new ListBuilder<ImportProjectChoices>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineObject179ExcludeEnum)]), () => new ListBuilder<InlineObject179ExcludeEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineResponse4033Errors)]), () => new ListBuilder<InlineResponse4033Errors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineResponse422Errors)]), () => new ListBuilder<InlineResponse422Errors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineResponse422Errors)]), () => new ListBuilder<InlineResponse422Errors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineResponse422Errors)]), () => new ListBuilder<InlineResponse422Errors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(InlineResponse5031Errors)]), () => new ListBuilder<InlineResponse5031Errors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Installation)]), () => new ListBuilder<Installation>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(IssueSearchResultItem)]), () => new ListBuilder<IssueSearchResultItem>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Job)]), () => new ListBuilder<Job>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JobSteps)]), () => new ListBuilder<JobSteps>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TopicSearchResultItemRelated)]), () => new ListBuilder<TopicSearchResultItemRelated>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TopicSearchResultItemRelated)]), () => new ListBuilder<TopicSearchResultItemRelated>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Label)]), () => new ListBuilder<Label>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(LabelSearchResultItem)]), () => new ListBuilder<LabelSearchResultItem>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(LinkWithType)]), () => new ListBuilder<LinkWithType>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(MinimalRepository)]), () => new ListBuilder<MinimalRepository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(OrganizationActionsSecret)]), () => new ListBuilder<OrganizationActionsSecret>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(OrganizationSimple)]), () => new ListBuilder<OrganizationSimple>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups)]), () => new ListBuilder<OrgsOrgTeamsTeamSlugTeamSyncGroupMappingsGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PendingDeploymentReviewers)]), () => new ListBuilder<PendingDeploymentReviewers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PullRequestLabels)]), () => new ListBuilder<PullRequestLabels>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TeamSimple)]), () => new ListBuilder<TeamSimple>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PullRequestMinimal)]), () => new ListBuilder<PullRequestMinimal>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PullRequestMinimal)]), () => new ListBuilder<PullRequestMinimal>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PullRequestMinimal)]), () => new ListBuilder<PullRequestMinimal>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(PullRequestSimpleLabels)]), () => new ListBuilder<PullRequestSimpleLabels>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TeamSimple)]), () => new ListBuilder<TeamSimple>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ReleaseAsset)]), () => new ListBuilder<ReleaseAsset>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(RepoSearchResultItem)]), () => new ListBuilder<RepoSearchResultItem>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ReposOwnerRepoCheckSuitesPreferencesAutoTriggerChecks)]), () => new ListBuilder<ReposOwnerRepoCheckSuitesPreferencesAutoTriggerChecks>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ReposOwnerRepoEnvironmentsEnvironmentNameReviewers)]), () => new ListBuilder<ReposOwnerRepoEnvironmentsEnvironmentNameReviewers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ReposOwnerRepoGitTreesTree)]), () => new ListBuilder<ReposOwnerRepoGitTreesTree>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ReposOwnerRepoPullsPullNumberReviewsComments)]), () => new ListBuilder<ReposOwnerRepoPullsPullNumberReviewsComments>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Repository)]), () => new ListBuilder<Repository>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(RepositoryTemplateRepositoryOwner)]), () => new ListBuilder<RepositoryTemplateRepositoryOwner>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(BranchRestrictionPolicyTeams)]), () => new ListBuilder<BranchRestrictionPolicyTeams>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(BranchRestrictionPolicyApps)]), () => new ListBuilder<BranchRestrictionPolicyApps>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Runner)]), () => new ListBuilder<Runner>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Runner)]), () => new ListBuilder<Runner>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Runner)]), () => new ListBuilder<Runner>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(RunnerGroupsEnterprise)]), () => new ListBuilder<RunnerGroupsEnterprise>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(RunnerGroupsOrg)]), () => new ListBuilder<RunnerGroupsOrg>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(RunnerLabels)]), () => new ListBuilder<RunnerLabels>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2OrganizationsOrgUsersEmails)]), () => new ListBuilder<ScimV2OrganizationsOrgUsersEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleCommitStatus)]), () => new ListBuilder<SimpleCommitStatus>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(IssueSearchResultItemLabels)]), () => new ListBuilder<IssueSearchResultItemLabels>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Team)]), () => new ListBuilder<Team>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Team)]), () => new ListBuilder<Team>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(SimpleUser)]), () => new ListBuilder<SimpleUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TeamSimple)]), () => new ListBuilder<TeamSimple>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimEnterpriseUserEmails)]), () => new ListBuilder<ScimEnterpriseUserEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersGroups)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimGroupListEnterpriseMembers)]), () => new ListBuilder<ScimGroupListEnterpriseMembers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimGroupListEnterpriseMembers)]), () => new ListBuilder<ScimGroupListEnterpriseMembers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimGroupListEnterpriseResources)]), () => new ListBuilder<ScimGroupListEnterpriseResources>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimUser)]), () => new ListBuilder<ScimUser>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimUserEmails)]), () => new ListBuilder<ScimUserEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimUserOperations)]), () => new ListBuilder<ScimUserOperations>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimUserListEnterpriseEmails)]), () => new ListBuilder<ScimUserListEnterpriseEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersGroups)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimUserListEnterpriseResources)]), () => new ListBuilder<ScimUserListEnterpriseResources>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseGroupsMembers)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseGroupsMembers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseGroupsMembers)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseGroupsMembers>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersEmails)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersGroups)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersEmails)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2EnterprisesEnterpriseUsersGroups)]), () => new ListBuilder<ScimV2EnterprisesEnterpriseUsersGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2OrganizationsOrgUsersScimUserIdOperations)]), () => new ListBuilder<ScimV2OrganizationsOrgUsersScimUserIdOperations>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ScimV2OrganizationsOrgUsersScimUserIdEmails)]), () => new ListBuilder<ScimV2OrganizationsOrgUsersScimUserIdEmails>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TeamsTeamIdTeamSyncGroupMappingsGroups)]), () => new ListBuilder<TeamsTeamIdTeamSyncGroupMappingsGroups>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(TopicSearchResultItem)]), () => new ListBuilder<TopicSearchResultItem>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Traffic)]), () => new ListBuilder<Traffic>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Traffic)]), () => new ListBuilder<Traffic>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(UserSearchResultItem)]), () => new ListBuilder<UserSearchResultItem>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(ValidationErrorErrors)]), () => new ListBuilder<ValidationErrorErrors>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(Workflow)]), () => new ListBuilder<Workflow>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(WorkflowRun)]), () => new ListBuilder<WorkflowRun>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(int)]), () => new ListBuilder<int>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(BaseGistFiles)]), () => new MapBuilder<String, BaseGistFiles>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(JsonObject)]), () => new ListBuilder<JsonObject>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(GistSimpleFiles)]), () => new MapBuilder<String, GistSimpleFiles>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(GistsFiles)]), () => new MapBuilder<String, GistsFiles>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(JsonObject)]), () => new MapBuilder<String, JsonObject>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(String)]), () => new MapBuilder<String, String>())
      ..addBuilderFactory(const FullType(BuiltMap, const [const FullType(String), const FullType(String)]), () => new MapBuilder<String, String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>()))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
