// GENERATED CODE - DO NOT MODIFY BY HAND
// VERSION OF 2020-02-08T14:10:08.685302

const languagesColor = <String, String>{
  '1C Enterprise': '#814CCC',
  '4D': '#ededed',
  'ABAP': '#E8274B',
  'ABNF': '#ededed',
  'AGS Script': '#B9D9FF',
  'AMPL': '#E6EFBB',
  'ANTLR': '#9DC3FF',
  'API Blueprint': '#2ACCA8',
  'APL': '#5A8164',
  'ASN.1': '#ededed',
  'ASP': '#6A40FD',
  'ATS': '#1AC620',
  'ActionScript': '#882B0F',
  'Ada': '#02F88C',
  'Adobe Font Metrics': '#ededed',
  'Agda': '#315665',
  'Alloy': '#64C800',
  'Alpine Abuild': '#ededed',
  'Altium Designer': '#ededed',
  'AngelScript': '#C7D7DC',
  'Ant Build System': '#ededed',
  'ApacheConf': '#ededed',
  'Apex': '#ededed',
  'Apollo Guidance Computer': '#ededed',
  'AppleScript': '#101F1F',
  'Arc': '#AA2AFE',
  'AsciiDoc': '#ededed',
  'AspectJ': '#A957B0',
  'Assembly': '#6E4C13',
  'Asymptote': '#4A0C0C',
  'Augeas': '#ededed',
  'AutoHotkey': '#6594B9',
  'AutoIt': '#1C3552',
  'Awk': '#ededed',
  'Ballerina': '#FF5000',
  'Batchfile': '#C1F12E',
  'Befunge': '#ededed',
  'BibTeX': '#ededed',
  'Bison': '#ededed',
  'BitBake': '#ededed',
  'Blade': '#ededed',
  'BlitzBasic': '#ededed',
  'BlitzMax': '#CD6400',
  'Bluespec': '#ededed',
  'Boo': '#D4BEC1',
  'Brainfuck': '#2F2530',
  'Brightscript': '#ededed',
  'C': '#555555',
  'C#': '#178600',
  'C++': '#F34B7D',
  'C-ObjDump': '#ededed',
  'C2hs Haskell': '#ededed',
  'CLIPS': '#ededed',
  'CMake': '#ededed',
  'COBOL': '#ededed',
  'COLLADA': '#ededed',
  'CSON': '#ededed',
  'CSS': '#563D7C',
  'CSV': '#ededed',
  'CWeb': '#ededed',
  'Cabal Config': '#ededed',
  'Cap\'n Proto': '#ededed',
  'CartoCSS': '#ededed',
  'Ceylon': '#DFA535',
  'Chapel': '#8DC63F',
  'Charity': '#ededed',
  'ChucK': '#ededed',
  'Cirru': '#CCCCFF',
  'Clarion': '#DB901E',
  'Clean': '#3F85AF',
  'Click': '#E4E6F3',
  'Clojure': '#DB5855',
  'Closure Templates': '#ededed',
  'Cloud Firestore Security Rules': '#ededed',
  'CoNLL-U': '#ededed',
  'CoffeeScript': '#244776',
  'ColdFusion': '#ED2CD6',
  'ColdFusion CFC': '#ededed',
  'Common Lisp': '#3FB68B',
  'Common Workflow Language': '#B5314C',
  'Component Pascal': '#B0CE4E',
  'Cool': '#ededed',
  'Coq': '#ededed',
  'Cpp-ObjDump': '#ededed',
  'Creole': '#ededed',
  'Crystal': '#000100',
  'Csound': '#ededed',
  'Csound Document': '#ededed',
  'Csound Score': '#ededed',
  'Cuda': '#3A4E3A',
  'Cycript': '#ededed',
  'Cython': '#ededed',
  'D': '#BA595E',
  'D-ObjDump': '#ededed',
  'DIGITAL Command Language': '#ededed',
  'DM': '#447265',
  'DNS Zone': '#ededed',
  'DTrace': '#ededed',
  'Darcs Patch': '#ededed',
  'Dart': '#00B4AB',
  'DataWeave': '#003A52',
  'Dhall': '#DFAFFF',
  'Diff': '#ededed',
  'DirectX 3D File': '#ededed',
  'Dockerfile': '#384D54',
  'Dogescript': '#CCA760',
  'Dylan': '#6C616E',
  'E': '#CCCE35',
  'EBNF': '#ededed',
  'ECL': '#8A1267',
  'ECLiPSe': '#ededed',
  'EJS': '#ededed',
  'EML': '#ededed',
  'EQ': '#A78649',
  'Eagle': '#ededed',
  'Easybuild': '#ededed',
  'Ecere Projects': '#ededed',
  'EditorConfig': '#ededed',
  'Edje Data Collection': '#ededed',
  'Eiffel': '#946D57',
  'Elixir': '#6E4A7E',
  'Elm': '#60B5CC',
  'Emacs Lisp': '#C065DB',
  'EmberScript': '#FFF4F3',
  'Erlang': '#B83998',
  'F#': '#B845FC',
  'F*': '#572E30',
  'FIGlet Font': '#ededed',
  'FLUX': '#88CCFF',
  'Factor': '#636746',
  'Fancy': '#7B9DB4',
  'Fantom': '#14253C',
  'Faust': '#C37240',
  'Filebench WML': '#ededed',
  'Filterscript': '#ededed',
  'Formatted': '#ededed',
  'Forth': '#341708',
  'Fortran': '#4D41B1',
  'FreeMarker': '#0050B2',
  'Frege': '#00CAFE',
  'G-code': '#D08CF2',
  'GAML': '#FFC766',
  'GAMS': '#ededed',
  'GAP': '#ededed',
  'GCC Machine Description': '#ededed',
  'GDB': '#ededed',
  'GDScript': '#355570',
  'GLSL': '#ededed',
  'GN': '#ededed',
  'Game Maker Language': '#71B417',
  'Genie': '#FB855D',
  'Genshi': '#ededed',
  'Gentoo Ebuild': '#ededed',
  'Gentoo Eclass': '#ededed',
  'Gerber Image': '#ededed',
  'Gettext Catalog': '#ededed',
  'Gherkin': '#5B2063',
  'Git Attributes': '#ededed',
  'Git Config': '#ededed',
  'Glyph': '#C1AC7F',
  'Glyph Bitmap Distribution Format': '#ededed',
  'Gnuplot': '#F0A9F0',
  'Go': '#00ADD8',
  'Golo': '#88562A',
  'Gosu': '#82937F',
  'Grace': '#ededed',
  'Gradle': '#ededed',
  'Grammatical Framework': '#79AA7A',
  'Graph Modeling Language': '#ededed',
  'GraphQL': '#ededed',
  'Graphviz (DOT)': '#ededed',
  'Groovy': '#E69F56',
  'Groovy Server Pages': '#ededed',
  'HAProxy': '#ededed',
  'HCL': '#ededed',
  'HLSL': '#ededed',
  'HTML': '#E34C26',
  'HTML+Django': '#ededed',
  'HTML+ECR': '#ededed',
  'HTML+EEX': '#ededed',
  'HTML+ERB': '#ededed',
  'HTML+PHP': '#ededed',
  'HTML+Razor': '#ededed',
  'HTTP': '#ededed',
  'HXML': '#ededed',
  'Hack': '#878787',
  'Haml': '#ededed',
  'Handlebars': '#ededed',
  'Harbour': '#0E60E3',
  'Haskell': '#5E5086',
  'Haxe': '#DF7900',
  'HiveQL': '#DCE200',
  'HolyC': '#FFEFAF',
  'Hy': '#7790B2',
  'HyPhy': '#ededed',
  'IDL': '#A3522F',
  'IGOR Pro': '#0000CC',
  'INI': '#ededed',
  'IRC log': '#ededed',
  'Idris': '#B30000',
  'Ignore List': '#ededed',
  'Inform 7': '#ededed',
  'Inno Setup': '#ededed',
  'Io': '#A9188D',
  'Ioke': '#078193',
  'Isabelle': '#FEFE00',
  'Isabelle ROOT': '#ededed',
  'J': '#9EEDFF',
  'JFlex': '#ededed',
  'JSON': '#ededed',
  'JSON with Comments': '#ededed',
  'JSON5': '#ededed',
  'JSONLD': '#ededed',
  'JSONiq': '#40D47E',
  'JSX': '#ededed',
  'Jasmin': '#ededed',
  'Java': '#B07219',
  'Java Properties': '#ededed',
  'Java Server Pages': '#ededed',
  'JavaScript': '#F1E05A',
  'JavaScript+ERB': '#ededed',
  'Jison': '#ededed',
  'Jison Lex': '#ededed',
  'Jolie': '#843179',
  'Jsonnet': '#0064BD',
  'Julia': '#A270BA',
  'Jupyter Notebook': '#DA5B0B',
  'KRL': '#28430A',
  'KiCad Layout': '#ededed',
  'KiCad Legacy Layout': '#ededed',
  'KiCad Schematic': '#ededed',
  'Kit': '#ededed',
  'Kotlin': '#F18E33',
  'LFE': '#4C3023',
  'LLVM': '#185619',
  'LOLCODE': '#CC9900',
  'LSL': '#3D9970',
  'LTspice Symbol': '#ededed',
  'LabVIEW': '#ededed',
  'Lasso': '#999999',
  'Latte': '#ededed',
  'Lean': '#ededed',
  'Less': '#ededed',
  'Lex': '#DBCA00',
  'LilyPond': '#ededed',
  'Limbo': '#ededed',
  'Linker Script': '#ededed',
  'Linux Kernel Module': '#ededed',
  'Liquid': '#ededed',
  'Literate Agda': '#ededed',
  'Literate CoffeeScript': '#ededed',
  'Literate Haskell': '#ededed',
  'LiveScript': '#499886',
  'Logos': '#ededed',
  'Logtalk': '#ededed',
  'LookML': '#652B81',
  'LoomScript': '#ededed',
  'Lua': '#000080',
  'M': '#ededed',
  'M4': '#ededed',
  'M4Sugar': '#ededed',
  'MATLAB': '#E16737',
  'MAXScript': '#00A6A6',
  'MLIR': '#5EC8DB',
  'MQL4': '#62A8D6',
  'MQL5': '#4A76B8',
  'MTML': '#B7E1F4',
  'MUF': '#ededed',
  'Makefile': '#427819',
  'Mako': '#ededed',
  'Markdown': '#ededed',
  'Marko': '#ededed',
  'Mask': '#F97732',
  'Mathematica': '#ededed',
  'Maven POM': '#ededed',
  'Max': '#C4A79C',
  'MediaWiki': '#ededed',
  'Mercury': '#FF2B2B',
  'Meson': '#007800',
  'Metal': '#8F14E9',
  'Microsoft Developer Studio Project': '#ededed',
  'MiniD': '#ededed',
  'Mirah': '#C7A938',
  'Modelica': '#ededed',
  'Modula-2': '#ededed',
  'Modula-3': '#223388',
  'Module Management System': '#ededed',
  'Monkey': '#ededed',
  'Moocode': '#ededed',
  'MoonScript': '#ededed',
  'Motorola 68K Assembly': '#ededed',
  'Muse': '#ededed',
  'Myghty': '#ededed',
  'NCL': '#28431F',
  'NL': '#ededed',
  'NPM Config': '#ededed',
  'NSIS': '#ededed',
  'Nearley': '#990000',
  'Nemerle': '#3D3C6E',
  'NetLinx': '#0AA0FF',
  'NetLinx+ERB': '#747FAA',
  'NetLogo': '#FF6375',
  'NewLisp': '#87AED7',
  'Nextflow': '#3AC486',
  'Nginx': '#ededed',
  'Nim': '#37775B',
  'Ninja': '#ededed',
  'Nit': '#009917',
  'Nix': '#7E7EFF',
  'Nu': '#C9DF40',
  'NumPy': '#ededed',
  'OCaml': '#3BE133',
  'ObjDump': '#ededed',
  'Object Data Instance Notation': '#ededed',
  'ObjectScript': '#424893',
  'Objective-C': '#438EFF',
  'Objective-C++': '#6866FB',
  'Objective-J': '#FF0C5A',
  'Odin': '#60AFFE',
  'Omgrofl': '#CABBFF',
  'Opa': '#ededed',
  'Opal': '#F7EDE0',
  'Open Policy Agent': '#ededed',
  'OpenCL': '#ededed',
  'OpenEdge ABL': '#ededed',
  'OpenRC runscript': '#ededed',
  'OpenSCAD': '#ededed',
  'OpenStep Property List': '#ededed',
  'OpenType Feature File': '#ededed',
  'Org': '#ededed',
  'Ox': '#ededed',
  'Oxygene': '#CDD0E3',
  'Oz': '#FAB738',
  'P4': '#7055B5',
  'PHP': '#4F5D95',
  'PLSQL': '#DAD8D8',
  'PLpgSQL': '#ededed',
  'POV-Ray SDL': '#ededed',
  'Pan': '#CC0000',
  'Papyrus': '#6600CC',
  'Parrot': '#F3CA0A',
  'Parrot Assembly': '#ededed',
  'Parrot Internal Representation': '#ededed',
  'Pascal': '#E3F171',
  'Pawn': '#DBB284',
  'Pep8': '#C76F5B',
  'Perl': '#0298C3',
  'Pic': '#ededed',
  'Pickle': '#ededed',
  'PicoLisp': '#ededed',
  'PigLatin': '#FCD7DE',
  'Pike': '#005390',
  'Pod': '#ededed',
  'Pod 6': '#ededed',
  'PogoScript': '#D80074',
  'Pony': '#ededed',
  'PostCSS': '#ededed',
  'PostScript': '#DA291C',
  'PowerBuilder': '#8F0F8D',
  'PowerShell': '#012456',
  'Prisma': '#ededed',
  'Processing': '#0096D8',
  'Proguard': '#ededed',
  'Prolog': '#74283C',
  'Propeller Spin': '#7FA2A7',
  'Protocol Buffer': '#ededed',
  'Public Key': '#ededed',
  'Pug': '#ededed',
  'Puppet': '#302B6D',
  'Pure Data': '#ededed',
  'PureBasic': '#5A6986',
  'PureScript': '#1D222D',
  'Python': '#3572A5',
  'Python console': '#ededed',
  'Python traceback': '#ededed',
  'QML': '#44A51C',
  'QMake': '#ededed',
  'Quake': '#882233',
  'R': '#198CE7',
  'RAML': '#77D9FB',
  'RDoc': '#ededed',
  'REALbasic': '#ededed',
  'REXX': '#ededed',
  'RHTML': '#ededed',
  'RMarkdown': '#ededed',
  'RPC': '#ededed',
  'RPM Spec': '#ededed',
  'RUNOFF': '#665A4E',
  'Racket': '#3C5CAA',
  'Ragel': '#9D5200',
  'Raku': '#0000FB',
  'Rascal': '#FFFAA0',
  'Raw token data': '#ededed',
  'Readline Config': '#ededed',
  'Reason': '#FF5847',
  'Rebol': '#358A5B',
  'Red': '#F50000',
  'Redcode': '#ededed',
  'Regular Expression': '#ededed',
  'Ren\'Py': '#FF7F7F',
  'RenderScript': '#ededed',
  'Rich Text Format': '#ededed',
  'Ring': '#2D54CB',
  'Riot': '#A71E49',
  'RobotFramework': '#ededed',
  'Roff': '#ECDEBE',
  'Roff Manpage': '#ededed',
  'Rouge': '#CC0088',
  'Ruby': '#701516',
  'Rust': '#DEA584',
  'SAS': '#B34936',
  'SCSS': '#ededed',
  'SMT': '#ededed',
  'SPARQL': '#ededed',
  'SQF': '#3F3F3F',
  'SQL': '#ededed',
  'SQLPL': '#ededed',
  'SRecode Template': '#348A34',
  'SSH Config': '#ededed',
  'STON': '#ededed',
  'SVG': '#ededed',
  'SWIG': '#ededed',
  'Sage': '#ededed',
  'SaltStack': '#646464',
  'Sass': '#ededed',
  'Scala': '#C22D40',
  'Scaml': '#ededed',
  'Scheme': '#1E4AEC',
  'Scilab': '#ededed',
  'Self': '#0579AA',
  'ShaderLab': '#ededed',
  'Shell': '#89E051',
  'ShellSession': '#ededed',
  'Shen': '#120F14',
  'Slash': '#007EFF',
  'Slice': '#003FA2',
  'Slim': '#ededed',
  'SmPL': '#C94949',
  'Smali': '#ededed',
  'Smalltalk': '#596706',
  'Smarty': '#ededed',
  'Solidity': '#AA6746',
  'SourcePawn': '#5C7611',
  'Spline Font Database': '#ededed',
  'Squirrel': '#800000',
  'Stan': '#B2011D',
  'Standard ML': '#DC566D',
  'Starlark': '#76D275',
  'Stata': '#ededed',
  'Stylus': '#ededed',
  'SubRip Text': '#ededed',
  'SugarSS': '#ededed',
  'SuperCollider': '#46390B',
  'Svelte': '#ededed',
  'Swift': '#FFAC45',
  'SystemVerilog': '#DAE1C2',
  'TI Program': '#A0AA87',
  'TLA': '#ededed',
  'TOML': '#ededed',
  'TSQL': '#ededed',
  'TSX': '#ededed',
  'TXL': '#ededed',
  'Tcl': '#E4CC98',
  'Tcsh': '#ededed',
  'TeX': '#3D6117',
  'Tea': '#ededed',
  'Terra': '#00004C',
  'Texinfo': '#ededed',
  'Text': '#ededed',
  'Textile': '#ededed',
  'Thrift': '#ededed',
  'Turing': '#CF142B',
  'Turtle': '#ededed',
  'Twig': '#ededed',
  'Type Language': '#ededed',
  'TypeScript': '#2B7489',
  'Unified Parallel C': '#ededed',
  'Unity3D Asset': '#ededed',
  'Unix Assembly': '#ededed',
  'Uno': '#ededed',
  'UnrealScript': '#A54C4D',
  'UrWeb': '#ededed',
  'V': '#5D87BD',
  'VBA': '#867DB1',
  'VBScript': '#15DCDC',
  'VCL': '#148AA8',
  'VHDL': '#ADB2CB',
  'Vala': '#FBE5CD',
  'Verilog': '#B2B7F8',
  'Vim Snippet': '#ededed',
  'Vim script': '#199F4B',
  'Visual Basic .NET': '#945DB7',
  'Volt': '#1F1F1F',
  'Vue': '#2C3E50',
  'Wavefront Material': '#ededed',
  'Wavefront Object': '#ededed',
  'Web Ontology Language': '#ededed',
  'WebAssembly': '#04133B',
  'WebIDL': '#ededed',
  'WebVTT': '#ededed',
  'Wget Config': '#ededed',
  'Windows Registry Entries': '#ededed',
  'Wollok': '#A23738',
  'World of Warcraft Addon Data': '#ededed',
  'X BitMap': '#ededed',
  'X Font Directory Index': '#ededed',
  'X PixMap': '#ededed',
  'X10': '#4B6BEF',
  'XC': '#99DA07',
  'XCompose': '#ededed',
  'XML': '#ededed',
  'XML Property List': '#ededed',
  'XPages': '#ededed',
  'XProc': '#ededed',
  'XQuery': '#5232E7',
  'XS': '#ededed',
  'XSLT': '#EB8CEB',
  'Xojo': '#ededed',
  'Xtend': '#ededed',
  'YAML': '#ededed',
  'YANG': '#ededed',
  'YARA': '#220000',
  'YASnippet': '#32AB90',
  'Yacc': '#4B6C4B',
  'ZAP': '#0D665E',
  'ZIL': '#DC75E5',
  'Zeek': '#ededed',
  'ZenScript': '#00BCD1',
  'Zephir': '#118F9E',
  'Zig': '#EC915C',
  'Zimpl': '#ededed',
  'cURL Config': '#ededed',
  'desktop': '#ededed',
  'dircolors': '#ededed',
  'eC': '#913960',
  'edn': '#ededed',
  'fish': '#ededed',
  'mIRC Script': '#926059',
  'mcfunction': '#E22837',
  'mupad': '#ededed',
  'nanorc': '#ededed',
  'nesC': '#94B0C7',
  'ooc': '#B0B77E',
  'q': '#0040CD',
  'reStructuredText': '#ededed',
  'sed': '#64B970',
  'wdl': '#42F1F4',
  'wisp': '#7582D1',
  'xBase': '#403A40',
};
