// GENERATED CODE - DO NOT MODIFY BY HAND
// VERSION OF 2020-10-03T23:56:33.788466

const languageColors = <String, String>{
  '1C Enterprise': '#814CCC',
  '4D': '#EDEDED',
  'ABAP': '#E8274B',
  'ABNF': '#EDEDED',
  'AGS Script': '#B9D9FF',
  'AL': '#3AA2B5',
  'AMPL': '#E6EFBB',
  'ANTLR': '#9DC3FF',
  'API Blueprint': '#2ACCA8',
  'APL': '#5A8164',
  'ASL': '#EDEDED',
  'ASN.1': '#EDEDED',
  'ASP.NET': '#9400FF',
  'ATS': '#1AC620',
  'ActionScript': '#882B0F',
  'Ada': '#02F88C',
  'Adobe Font Metrics': '#EDEDED',
  'Agda': '#315665',
  'Alloy': '#64C800',
  'Alpine Abuild': '#EDEDED',
  'Altium Designer': '#EDEDED',
  'AngelScript': '#C7D7DC',
  'Ant Build System': '#EDEDED',
  'ApacheConf': '#EDEDED',
  'Apex': '#1797C0',
  'Apollo Guidance Computer': '#0B3D91',
  'AppleScript': '#101F1F',
  'Arc': '#AA2AFE',
  'AsciiDoc': '#EDEDED',
  'AspectJ': '#A957B0',
  'Assembly': '#6E4C13',
  'Asymptote': '#FF0000',
  'Augeas': '#EDEDED',
  'AutoHotkey': '#6594B9',
  'AutoIt': '#1C3552',
  'Avro IDL': '#EDEDED',
  'Awk': '#EDEDED',
  'Ballerina': '#FF5000',
  'Batchfile': '#C1F12E',
  'Befunge': '#EDEDED',
  'BibTeX': '#EDEDED',
  'Bison': '#6A463F',
  'BitBake': '#EDEDED',
  'Blade': '#F7523F',
  'BlitzBasic': '#EDEDED',
  'BlitzMax': '#CD6400',
  'Bluespec': '#EDEDED',
  'Boo': '#D4BEC1',
  'Brainfuck': '#2F2530',
  'Brightscript': '#EDEDED',
  'C': '#555555',
  'C#': '#178600',
  'C++': '#F34B7D',
  'C-ObjDump': '#EDEDED',
  'C2hs Haskell': '#EDEDED',
  'CLIPS': '#EDEDED',
  'CMake': '#EDEDED',
  'COBOL': '#EDEDED',
  'COLLADA': '#EDEDED',
  'CSON': '#244776',
  'CSS': '#563D7C',
  'CSV': '#EDEDED',
  'CWeb': '#EDEDED',
  'Cabal Config': '#EDEDED',
  'Cap\'n Proto': '#EDEDED',
  'CartoCSS': '#EDEDED',
  'Ceylon': '#DFA535',
  'Chapel': '#8DC63F',
  'Charity': '#EDEDED',
  'ChucK': '#EDEDED',
  'Cirru': '#CCCCFF',
  'Clarion': '#DB901E',
  'Classic ASP': '#6A40FD',
  'Clean': '#3F85AF',
  'Click': '#E4E6F3',
  'Clojure': '#DB5855',
  'Closure Templates': '#EDEDED',
  'Cloud Firestore Security Rules': '#EDEDED',
  'CoNLL-U': '#EDEDED',
  'CodeQL': '#EDEDED',
  'CoffeeScript': '#244776',
  'ColdFusion': '#ED2CD6',
  'ColdFusion CFC': '#ED2CD6',
  'Common Lisp': '#3FB68B',
  'Common Workflow Language': '#B5314C',
  'Component Pascal': '#B0CE4E',
  'Cool': '#EDEDED',
  'Coq': '#EDEDED',
  'Cpp-ObjDump': '#EDEDED',
  'Creole': '#EDEDED',
  'Crystal': '#000100',
  'Csound': '#EDEDED',
  'Csound Document': '#EDEDED',
  'Csound Score': '#EDEDED',
  'Cuda': '#3A4E3A',
  'Cycript': '#EDEDED',
  'Cython': '#EDEDED',
  'D': '#BA595E',
  'D-ObjDump': '#EDEDED',
  'DIGITAL Command Language': '#EDEDED',
  'DM': '#447265',
  'DNS Zone': '#EDEDED',
  'DTrace': '#EDEDED',
  'Dafny': '#FFEC25',
  'Darcs Patch': '#EDEDED',
  'Dart': '#00B4AB',
  'DataWeave': '#003A52',
  'Dhall': '#DFAFFF',
  'Diff': '#EDEDED',
  'DirectX 3D File': '#EDEDED',
  'Dockerfile': '#384D54',
  'Dogescript': '#CCA760',
  'Dylan': '#6C616E',
  'E': '#CCCE35',
  'EBNF': '#EDEDED',
  'ECL': '#8A1267',
  'ECLiPSe': '#EDEDED',
  'EJS': '#A91E50',
  'EML': '#EDEDED',
  'EQ': '#A78649',
  'Eagle': '#EDEDED',
  'Easybuild': '#EDEDED',
  'Ecere Projects': '#EDEDED',
  'EditorConfig': '#EDEDED',
  'Edje Data Collection': '#EDEDED',
  'Eiffel': '#4D6977',
  'Elixir': '#6E4A7E',
  'Elm': '#60B5CC',
  'Emacs Lisp': '#C065DB',
  'EmberScript': '#FFF4F3',
  'Erlang': '#B83998',
  'F#': '#B845FC',
  'F*': '#572E30',
  'FIGlet Font': '#EDEDED',
  'FLUX': '#88CCFF',
  'Factor': '#636746',
  'Fancy': '#7B9DB4',
  'Fantom': '#14253C',
  'Faust': '#C37240',
  'Filebench WML': '#EDEDED',
  'Filterscript': '#EDEDED',
  'Formatted': '#EDEDED',
  'Forth': '#341708',
  'Fortran': '#4D41B1',
  'Fortran Free Form': '#EDEDED',
  'FreeMarker': '#0050B2',
  'Frege': '#00CAFE',
  'Futhark': '#5F021F',
  'G-code': '#D08CF2',
  'GAML': '#FFC766',
  'GAMS': '#EDEDED',
  'GAP': '#EDEDED',
  'GCC Machine Description': '#EDEDED',
  'GDB': '#EDEDED',
  'GDScript': '#355570',
  'GEDCOM': '#EDEDED',
  'GLSL': '#EDEDED',
  'GN': '#EDEDED',
  'Game Maker Language': '#71B417',
  'Genie': '#FB855D',
  'Genshi': '#EDEDED',
  'Gentoo Ebuild': '#EDEDED',
  'Gentoo Eclass': '#EDEDED',
  'Gerber Image': '#EDEDED',
  'Gettext Catalog': '#EDEDED',
  'Gherkin': '#5B2063',
  'Git Attributes': '#EDEDED',
  'Git Config': '#EDEDED',
  'Glyph': '#C1AC7F',
  'Glyph Bitmap Distribution Format': '#EDEDED',
  'Gnuplot': '#F0A9F0',
  'Go': '#00ADD8',
  'Golo': '#88562A',
  'Gosu': '#82937F',
  'Grace': '#EDEDED',
  'Gradle': '#EDEDED',
  'Grammatical Framework': '#FF0000',
  'Graph Modeling Language': '#EDEDED',
  'GraphQL': '#E10098',
  'Graphviz (DOT)': '#EDEDED',
  'Groovy': '#E69F56',
  'Groovy Server Pages': '#EDEDED',
  'HAProxy': '#EDEDED',
  'HCL': '#EDEDED',
  'HLSL': '#EDEDED',
  'HTML': '#E34C26',
  'HTML+Django': '#EDEDED',
  'HTML+ECR': '#EDEDED',
  'HTML+EEX': '#EDEDED',
  'HTML+ERB': '#EDEDED',
  'HTML+PHP': '#EDEDED',
  'HTML+Razor': '#EDEDED',
  'HTTP': '#EDEDED',
  'HXML': '#EDEDED',
  'Hack': '#878787',
  'Haml': '#ECE2A9',
  'Handlebars': '#F7931E',
  'Harbour': '#0E60E3',
  'Haskell': '#5E5086',
  'Haxe': '#DF7900',
  'HiveQL': '#DCE200',
  'HolyC': '#FFEFAF',
  'Hy': '#7790B2',
  'HyPhy': '#EDEDED',
  'IDL': '#A3522F',
  'IGOR Pro': '#0000CC',
  'INI': '#EDEDED',
  'IRC log': '#EDEDED',
  'Idris': '#B30000',
  'Ignore List': '#EDEDED',
  'Inform 7': '#EDEDED',
  'Inno Setup': '#EDEDED',
  'Io': '#A9188D',
  'Ioke': '#078193',
  'Isabelle': '#FEFE00',
  'Isabelle ROOT': '#EDEDED',
  'J': '#9EEDFF',
  'JFlex': '#DBCA00',
  'JSON': '#EDEDED',
  'JSON with Comments': '#EDEDED',
  'JSON5': '#EDEDED',
  'JSONLD': '#EDEDED',
  'JSONiq': '#40D47E',
  'JSX': '#EDEDED',
  'Jasmin': '#EDEDED',
  'Java': '#B07219',
  'Java Properties': '#EDEDED',
  'Java Server Pages': '#EDEDED',
  'JavaScript': '#F1E05A',
  'JavaScript+ERB': '#EDEDED',
  'Jison': '#EDEDED',
  'Jison Lex': '#EDEDED',
  'Jolie': '#843179',
  'Jsonnet': '#0064BD',
  'Julia': '#A270BA',
  'Jupyter Notebook': '#DA5B0B',
  'KRL': '#28430A',
  'Kaitai Struct': '#773B37',
  'KiCad Layout': '#EDEDED',
  'KiCad Legacy Layout': '#EDEDED',
  'KiCad Schematic': '#EDEDED',
  'Kit': '#EDEDED',
  'Kotlin': '#F18E33',
  'LFE': '#4C3023',
  'LLVM': '#185619',
  'LOLCODE': '#CC9900',
  'LSL': '#3D9970',
  'LTspice Symbol': '#EDEDED',
  'LabVIEW': '#EDEDED',
  'Lasso': '#999999',
  'Latte': '#F2A542',
  'Lean': '#EDEDED',
  'Less': '#1D365D',
  'Lex': '#DBCA00',
  'LilyPond': '#EDEDED',
  'Limbo': '#EDEDED',
  'Linker Script': '#EDEDED',
  'Linux Kernel Module': '#EDEDED',
  'Liquid': '#EDEDED',
  'Literate Agda': '#EDEDED',
  'Literate CoffeeScript': '#EDEDED',
  'Literate Haskell': '#EDEDED',
  'LiveScript': '#499886',
  'Logos': '#EDEDED',
  'Logtalk': '#EDEDED',
  'LookML': '#652B81',
  'LoomScript': '#EDEDED',
  'Lua': '#000080',
  'M': '#EDEDED',
  'M4': '#EDEDED',
  'M4Sugar': '#EDEDED',
  'MATLAB': '#E16737',
  'MAXScript': '#00A6A6',
  'MLIR': '#5EC8DB',
  'MQL4': '#62A8D6',
  'MQL5': '#4A76B8',
  'MTML': '#B7E1F4',
  'MUF': '#EDEDED',
  'Macaulay2': '#D8FFFF',
  'Makefile': '#427819',
  'Mako': '#EDEDED',
  'Markdown': '#083FA1',
  'Marko': '#42BFF2',
  'Mask': '#F97732',
  'Mathematica': '#EDEDED',
  'Maven POM': '#EDEDED',
  'Max': '#C4A79C',
  'MediaWiki': '#EDEDED',
  'Mercury': '#FF2B2B',
  'Meson': '#007800',
  'Metal': '#8F14E9',
  'Microsoft Developer Studio Project': '#EDEDED',
  'MiniD': '#EDEDED',
  'Mirah': '#C7A938',
  'Modelica': '#EDEDED',
  'Modula-2': '#EDEDED',
  'Modula-3': '#223388',
  'Module Management System': '#EDEDED',
  'Monkey': '#EDEDED',
  'Moocode': '#EDEDED',
  'MoonScript': '#EDEDED',
  'Motorola 68K Assembly': '#EDEDED',
  'Muse': '#EDEDED',
  'Mustache': '#EDEDED',
  'Myghty': '#EDEDED',
  'NASL': '#EDEDED',
  'NCL': '#28431F',
  'NEON': '#EDEDED',
  'NL': '#EDEDED',
  'NPM Config': '#EDEDED',
  'NSIS': '#EDEDED',
  'Nearley': '#990000',
  'Nemerle': '#3D3C6E',
  'NetLinx': '#0AA0FF',
  'NetLinx+ERB': '#747FAA',
  'NetLogo': '#FF6375',
  'NewLisp': '#87AED7',
  'Nextflow': '#3AC486',
  'Nginx': '#EDEDED',
  'Nim': '#FFC200',
  'Ninja': '#EDEDED',
  'Nit': '#009917',
  'Nix': '#7E7EFF',
  'Nu': '#C9DF40',
  'NumPy': '#9C8AF9',
  'OCaml': '#3BE133',
  'ObjDump': '#EDEDED',
  'Object Data Instance Notation': '#EDEDED',
  'ObjectScript': '#424893',
  'Objective-C': '#438EFF',
  'Objective-C++': '#6866FB',
  'Objective-J': '#FF0C5A',
  'Odin': '#60AFFE',
  'Omgrofl': '#CABBFF',
  'Opa': '#EDEDED',
  'Opal': '#F7EDE0',
  'Open Policy Agent': '#EDEDED',
  'OpenCL': '#EDEDED',
  'OpenEdge ABL': '#EDEDED',
  'OpenQASM': '#AA70FF',
  'OpenRC runscript': '#EDEDED',
  'OpenSCAD': '#EDEDED',
  'OpenStep Property List': '#EDEDED',
  'OpenType Feature File': '#EDEDED',
  'Org': '#EDEDED',
  'Ox': '#EDEDED',
  'Oxygene': '#CDD0E3',
  'Oz': '#FAB738',
  'P4': '#7055B5',
  'PHP': '#4F5D95',
  'PLSQL': '#DAD8D8',
  'PLpgSQL': '#EDEDED',
  'POV-Ray SDL': '#EDEDED',
  'Pan': '#CC0000',
  'Papyrus': '#6600CC',
  'Parrot': '#F3CA0A',
  'Parrot Assembly': '#EDEDED',
  'Parrot Internal Representation': '#EDEDED',
  'Pascal': '#E3F171',
  'Pawn': '#DBB284',
  'Pep8': '#C76F5B',
  'Perl': '#0298C3',
  'Pic': '#EDEDED',
  'Pickle': '#EDEDED',
  'PicoLisp': '#EDEDED',
  'PigLatin': '#FCD7DE',
  'Pike': '#005390',
  'PlantUML': '#EDEDED',
  'Pod': '#EDEDED',
  'Pod 6': '#EDEDED',
  'PogoScript': '#D80074',
  'Pony': '#EDEDED',
  'PostCSS': '#EDEDED',
  'PostScript': '#DA291C',
  'PowerBuilder': '#8F0F8D',
  'PowerShell': '#012456',
  'Prisma': '#0C344B',
  'Processing': '#0096D8',
  'Proguard': '#EDEDED',
  'Prolog': '#74283C',
  'Propeller Spin': '#7FA2A7',
  'Protocol Buffer': '#EDEDED',
  'Public Key': '#EDEDED',
  'Pug': '#A86454',
  'Puppet': '#302B6D',
  'Pure Data': '#EDEDED',
  'PureBasic': '#5A6986',
  'PureScript': '#1D222D',
  'Python': '#3572A5',
  'Python console': '#EDEDED',
  'Python traceback': '#EDEDED',
  'Q#': '#FED659',
  'QML': '#44A51C',
  'QMake': '#EDEDED',
  'Qt Script': '#00B841',
  'Quake': '#882233',
  'R': '#198CE7',
  'RAML': '#77D9FB',
  'RDoc': '#EDEDED',
  'REALbasic': '#EDEDED',
  'REXX': '#EDEDED',
  'RMarkdown': '#EDEDED',
  'RPC': '#EDEDED',
  'RPM Spec': '#EDEDED',
  'RUNOFF': '#665A4E',
  'Racket': '#3C5CAA',
  'Ragel': '#9D5200',
  'Raku': '#0000FB',
  'Rascal': '#FFFAA0',
  'Raw token data': '#EDEDED',
  'Readline Config': '#EDEDED',
  'Reason': '#FF5847',
  'Rebol': '#358A5B',
  'Red': '#F50000',
  'Redcode': '#EDEDED',
  'Regular Expression': '#EDEDED',
  'Ren\'Py': '#FF7F7F',
  'RenderScript': '#EDEDED',
  'Rich Text Format': '#EDEDED',
  'Ring': '#2D54CB',
  'Riot': '#A71E49',
  'RobotFramework': '#EDEDED',
  'Roff': '#ECDEBE',
  'Roff Manpage': '#EDEDED',
  'Rouge': '#CC0088',
  'Ruby': '#701516',
  'Rust': '#DEA584',
  'SAS': '#B34936',
  'SCSS': '#C6538C',
  'SMT': '#EDEDED',
  'SPARQL': '#EDEDED',
  'SQF': '#3F3F3F',
  'SQL': '#EDEDED',
  'SQLPL': '#EDEDED',
  'SRecode Template': '#348A34',
  'SSH Config': '#EDEDED',
  'STON': '#EDEDED',
  'SVG': '#FF9900',
  'SWIG': '#EDEDED',
  'Sage': '#EDEDED',
  'SaltStack': '#646464',
  'Sass': '#A53B70',
  'Scala': '#C22D40',
  'Scaml': '#EDEDED',
  'Scheme': '#1E4AEC',
  'Scilab': '#EDEDED',
  'Self': '#0579AA',
  'ShaderLab': '#EDEDED',
  'Shell': '#89E051',
  'ShellSession': '#EDEDED',
  'Shen': '#120F14',
  'Sieve': '#EDEDED',
  'Slash': '#007EFF',
  'Slice': '#003FA2',
  'Slim': '#2B2B2B',
  'SmPL': '#C94949',
  'Smali': '#EDEDED',
  'Smalltalk': '#596706',
  'Smarty': '#EDEDED',
  'Solidity': '#AA6746',
  'SourcePawn': '#F69E1D',
  'Spline Font Database': '#EDEDED',
  'Squirrel': '#800000',
  'Stan': '#B2011D',
  'Standard ML': '#DC566D',
  'Starlark': '#76D275',
  'Stata': '#EDEDED',
  'Stylus': '#FF6347',
  'SubRip Text': '#EDEDED',
  'SugarSS': '#EDEDED',
  'SuperCollider': '#46390B',
  'Svelte': '#FF3E00',
  'Swift': '#FFAC45',
  'SystemVerilog': '#DAE1C2',
  'TI Program': '#A0AA87',
  'TLA': '#EDEDED',
  'TOML': '#EDEDED',
  'TSQL': '#EDEDED',
  'TSV': '#EDEDED',
  'TSX': '#EDEDED',
  'TXL': '#EDEDED',
  'Tcl': '#E4CC98',
  'Tcsh': '#EDEDED',
  'TeX': '#3D6117',
  'Tea': '#EDEDED',
  'Terra': '#00004C',
  'Texinfo': '#EDEDED',
  'Text': '#EDEDED',
  'Textile': '#EDEDED',
  'Thrift': '#EDEDED',
  'Turing': '#CF142B',
  'Turtle': '#EDEDED',
  'Twig': '#C1D026',
  'Type Language': '#EDEDED',
  'TypeScript': '#2B7489',
  'Unified Parallel C': '#4E3617',
  'Unity3D Asset': '#EDEDED',
  'Unix Assembly': '#EDEDED',
  'Uno': '#9933CC',
  'UnrealScript': '#A54C4D',
  'UrWeb': '#EDEDED',
  'V': '#4F87C4',
  'VBA': '#867DB1',
  'VBScript': '#15DCDC',
  'VCL': '#148AA8',
  'VHDL': '#ADB2CB',
  'Vala': '#FBE5CD',
  'Verilog': '#B2B7F8',
  'Vim Help File': '#EDEDED',
  'Vim Snippet': '#EDEDED',
  'Vim script': '#199F4B',
  'Visual Basic .NET': '#945DB7',
  'Volt': '#1F1F1F',
  'Vue': '#2C3E50',
  'Wavefront Material': '#EDEDED',
  'Wavefront Object': '#EDEDED',
  'Web Ontology Language': '#EDEDED',
  'WebAssembly': '#04133B',
  'WebIDL': '#EDEDED',
  'WebVTT': '#EDEDED',
  'Wget Config': '#EDEDED',
  'Windows Registry Entries': '#EDEDED',
  'Wollok': '#A23738',
  'World of Warcraft Addon Data': '#EDEDED',
  'X BitMap': '#EDEDED',
  'X Font Directory Index': '#EDEDED',
  'X PixMap': '#EDEDED',
  'X10': '#4B6BEF',
  'XC': '#99DA07',
  'XCompose': '#EDEDED',
  'XML': '#EDEDED',
  'XML Property List': '#EDEDED',
  'XPages': '#EDEDED',
  'XProc': '#EDEDED',
  'XQuery': '#5232E7',
  'XS': '#EDEDED',
  'XSLT': '#EB8CEB',
  'Xojo': '#EDEDED',
  'Xtend': '#EDEDED',
  'YAML': '#CB171E',
  'YANG': '#EDEDED',
  'YARA': '#220000',
  'YASnippet': '#32AB90',
  'Yacc': '#4B6C4B',
  'ZAP': '#0D665E',
  'ZIL': '#DC75E5',
  'Zeek': '#EDEDED',
  'ZenScript': '#00BCD1',
  'Zephir': '#118F9E',
  'Zig': '#EC915C',
  'Zimpl': '#EDEDED',
  'cURL Config': '#EDEDED',
  'desktop': '#EDEDED',
  'dircolors': '#EDEDED',
  'eC': '#913960',
  'edn': '#EDEDED',
  'fish': '#EDEDED',
  'mIRC Script': '#3D57C3',
  'mcfunction': '#E22837',
  'mupad': '#EDEDED',
  'nanorc': '#EDEDED',
  'nesC': '#94B0C7',
  'ooc': '#B0B77E',
  'q': '#0040CD',
  'reStructuredText': '#EDEDED',
  'sed': '#64B970',
  'wdl': '#42F1F4',
  'wisp': '#7582D1',
  'xBase': '#403A40',
};
