const List<String> COMMON_GITHUB_TOKEN_ENV_KEYS = [
  'GITHUB_ADMIN_TOKEN',
  'GITHUB_DART_TOKEN',
  'GITHUB_API_TOKEN',
  'GITHUB_TOKEN',
  'HOMEBREW_GITHUB_API_TOKEN',
  'MACHINE_GITHUB_API_TOKEN'
];
