/// Json messages as dart string used for checks model tests.
library;

String checkSuiteString = checkSuiteTemplate('requested');

String checkSuiteTemplate(String action) => '''\
{
  "action": "$action",
  "check_suite": {
    "id": 118578147,
    "node_id": "MDEwOkNoZWNrU3VpdGUxMTg1NzgxNDc=",
    "head_branch": "changes",
    "head_sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
    "status": "completed",
    "conclusion": "success",
    "url": "https://api.github.com/repos/Codertocat/Hello-World/check-suites/118578147",
    "before": "6113728f27ae82c7b1a177c8d03f9e96e0adf246",
    "after": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
    "pull_requests": [
      {
        "url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2",
        "id": 279147437,
        "number": 2,
        "head": {
          "ref": "changes",
          "sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
          "repo": {
            "id": 186853002,
            "url": "https://api.github.com/repos/Codertocat/Hello-World",
            "name": "Hello-World"
          }
        },
        "base": {
          "ref": "master",
          "sha": "f95f852bd8fca8fcc58a9a2d6c842781e32a215e",
          "repo": {
            "id": 186853002,
            "url": "https://api.github.com/repos/Codertocat/Hello-World",
            "name": "Hello-World"
          }
        }
      }
    ],
    "app": {
      "id": 29310,
      "node_id": "MDM6QXBwMjkzMTA=",
      "owner": {
        "login": "Octocoders",
        "id": 38302899,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/38302899?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Octocoders",
        "html_url": "https://github.com/Octocoders",
        "followers_url": "https://api.github.com/users/Octocoders/followers",
        "following_url": "https://api.github.com/users/Octocoders/following{/other_user}",
        "gists_url": "https://api.github.com/users/Octocoders/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Octocoders/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Octocoders/subscriptions",
        "organizations_url": "https://api.github.com/users/Octocoders/orgs",
        "repos_url": "https://api.github.com/users/Octocoders/repos",
        "events_url": "https://api.github.com/users/Octocoders/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Octocoders/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "name": "octocoders-linter",
      "description": "",
      "external_url": "https://octocoders.io",
      "html_url": "https://github.com/apps/octocoders-linter",
      "created_at": "2019-04-19T19:36:24Z",
      "updated_at": "2019-04-19T19:36:56Z",
      "permissions": {
        "administration": "write",
        "checks": "write",
        "contents": "write",
        "deployments": "write",
        "issues": "write",
        "members": "write",
        "metadata": "read",
        "organization_administration": "write",
        "organization_hooks": "write",
        "organization_plan": "read",
        "organization_projects": "write",
        "organization_user_blocking": "write",
        "pages": "write",
        "pull_requests": "write",
        "repository_hooks": "write",
        "repository_projects": "write",
        "statuses": "write",
        "team_discussions": "write",
        "vulnerability_alerts": "read"
      },
      "events": []
    },
    "created_at": "2019-05-15T15:20:31Z",
    "updated_at": "2019-05-15T15:21:14Z",
    "latest_check_runs_count": 1,
    "check_runs_url": "https://api.github.com/repos/Codertocat/Hello-World/check-suites/118578147/check-runs",
    "head_commit": {
      "id": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
      "tree_id": "31b122c26a97cf9af023e9ddab94a82c6e77b0ea",
      "message": "Update README.md",
      "timestamp": "2019-05-15T15:20:30Z",
      "author": {
        "name": "Codertocat",
        "email": "21031067+Codertocat@users.noreply.github.com"
      },
      "committer": {
        "name": "Codertocat",
        "email": "21031067+Codertocat@users.noreply.github.com"
      }
    }
  },
  "repository": {
    "id": 186853002,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
    "name": "Hello-World",
    "full_name": "Codertocat/Hello-World",
    "private": false,
    "owner": {
      "login": "Codertocat",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Codertocat/Hello-World",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Codertocat/Hello-World",
    "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
    "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
    "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
    "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
    "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
    "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
    "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
    "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
    "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
    "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
    "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
    "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
    "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
    "created_at": "2019-05-15T15:19:25Z",
    "updated_at": "2019-05-15T15:21:14Z",
    "pushed_at": "2019-05-15T15:20:57Z",
    "git_url": "git://github.com/Codertocat/Hello-World.git",
    "ssh_url": "git@github.com:Codertocat/Hello-World.git",
    "clone_url": "https://github.com/Codertocat/Hello-World.git",
    "svn_url": "https://github.com/Codertocat/Hello-World",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Ruby",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 0,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "Codertocat",
    "id": 21031067,
    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Codertocat",
    "html_url": "https://github.com/Codertocat",
    "followers_url": "https://api.github.com/users/Codertocat/followers",
    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
    "repos_url": "https://api.github.com/users/Codertocat/repos",
    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
    "type": "User",
    "site_admin": false
  }
}
''';

const String checkRunString = '''
{
  "action": "created",
  "check_run": {
    "id": 128620228,
    "node_id": "MDg6Q2hlY2tSdW4xMjg2MjAyMjg=",
    "head_sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
    "external_id": "",
    "url": "https://api.github.com/repos/Codertocat/Hello-World/check-runs/128620228",
    "html_url": "https://github.com/Codertocat/Hello-World/runs/128620228",
    "details_url": "https://octocoders.io",
    "status": "queued",
    "conclusion": null,
    "started_at": "2019-05-15T15:21:12Z",
    "completed_at": null,
    "output": {
      "title": null,
      "summary": null,
      "text": null,
      "annotations_count": 0,
      "annotations_url": "https://api.github.com/repos/Codertocat/Hello-World/check-runs/128620228/annotations"
    },
    "name": "Octocoders-linter",
    "check_suite": {
      "id": 118578147,
      "node_id": "MDEwOkNoZWNrU3VpdGUxMTg1NzgxNDc=",
      "head_branch": "changes",
      "head_sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
      "status": "queued",
      "conclusion": null,
      "url": "https://api.github.com/repos/Codertocat/Hello-World/check-suites/118578147",
      "before": "6113728f27ae82c7b1a177c8d03f9e96e0adf246",
      "after": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
      "pull_requests": [
        {
          "url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2",
          "id": 279147437,
          "number": 2,
          "head": {
            "ref": "changes",
            "sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
            "repo": {
              "id": 186853002,
              "url": "https://api.github.com/repos/Codertocat/Hello-World",
              "name": "Hello-World"
            }
          },
          "base": {
            "ref": "master",
            "sha": "f95f852bd8fca8fcc58a9a2d6c842781e32a215e",
            "repo": {
              "id": 186853002,
              "url": "https://api.github.com/repos/Codertocat/Hello-World",
              "name": "Hello-World"
            }
          }
        }
      ],
      "app": {
        "id": 29310,
        "node_id": "MDM6QXBwMjkzMTA=",
        "owner": {
          "login": "Octocoders",
          "id": 38302899,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5",
          "avatar_url": "https://avatars1.githubusercontent.com/u/38302899?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Octocoders",
          "html_url": "https://github.com/Octocoders",
          "followers_url": "https://api.github.com/users/Octocoders/followers",
          "following_url": "https://api.github.com/users/Octocoders/following{/other_user}",
          "gists_url": "https://api.github.com/users/Octocoders/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Octocoders/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Octocoders/subscriptions",
          "organizations_url": "https://api.github.com/users/Octocoders/orgs",
          "repos_url": "https://api.github.com/users/Octocoders/repos",
          "events_url": "https://api.github.com/users/Octocoders/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Octocoders/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "name": "octocoders-linter",
        "description": "",
        "external_url": "https://octocoders.io",
        "html_url": "https://github.com/apps/octocoders-linter",
        "created_at": "2019-04-19T19:36:24Z",
        "updated_at": "2019-04-19T19:36:56Z",
        "permissions": {
          "administration": "write",
          "checks": "write",
          "contents": "write",
          "deployments": "write",
          "issues": "write",
          "members": "write",
          "metadata": "read",
          "organization_administration": "write",
          "organization_hooks": "write",
          "organization_plan": "read",
          "organization_projects": "write",
          "organization_user_blocking": "write",
          "pages": "write",
          "pull_requests": "write",
          "repository_hooks": "write",
          "repository_projects": "write",
          "statuses": "write",
          "team_discussions": "write",
          "vulnerability_alerts": "read"
        },
        "events": []
      },
      "created_at": "2019-05-15T15:20:31Z",
      "updated_at": "2019-05-15T15:20:31Z"
    },
    "app": {
      "id": 29310,
      "node_id": "MDM6QXBwMjkzMTA=",
      "owner": {
        "login": "Octocoders",
        "id": 38302899,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5",
        "avatar_url": "https://avatars1.githubusercontent.com/u/38302899?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Octocoders",
        "html_url": "https://github.com/Octocoders",
        "followers_url": "https://api.github.com/users/Octocoders/followers",
        "following_url": "https://api.github.com/users/Octocoders/following{/other_user}",
        "gists_url": "https://api.github.com/users/Octocoders/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Octocoders/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Octocoders/subscriptions",
        "organizations_url": "https://api.github.com/users/Octocoders/orgs",
        "repos_url": "https://api.github.com/users/Octocoders/repos",
        "events_url": "https://api.github.com/users/Octocoders/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Octocoders/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "name": "octocoders-linter",
      "description": "",
      "external_url": "https://octocoders.io",
      "html_url": "https://github.com/apps/octocoders-linter",
      "created_at": "2019-04-19T19:36:24Z",
      "updated_at": "2019-04-19T19:36:56Z",
      "permissions": {
        "administration": "write",
        "checks": "write",
        "contents": "write",
        "deployments": "write",
        "issues": "write",
        "members": "write",
        "metadata": "read",
        "organization_administration": "write",
        "organization_hooks": "write",
        "organization_plan": "read",
        "organization_projects": "write",
        "organization_user_blocking": "write",
        "pages": "write",
        "pull_requests": "write",
        "repository_hooks": "write",
        "repository_projects": "write",
        "statuses": "write",
        "team_discussions": "write",
        "vulnerability_alerts": "read"
      },
      "events": []
    },
    "pull_requests": [
      {
        "url": "https://api.github.com/repos/Codertocat/Hello-World/pulls/2",
        "id": 279147437,
        "number": 2,
        "head": {
          "ref": "changes",
          "sha": "ec26c3e57ca3a959ca5aad62de7213c562f8c821",
          "repo": {
            "id": 186853002,
            "url": "https://api.github.com/repos/Codertocat/Hello-World",
            "name": "Hello-World"
          }
        },
        "base": {
          "ref": "master",
          "sha": "f95f852bd8fca8fcc58a9a2d6c842781e32a215e",
          "repo": {
            "id": 186853002,
            "url": "https://api.github.com/repos/Codertocat/Hello-World",
            "name": "Hello-World"
          }
        }
      }
    ],
    "deployment": {
      "url": "https://api.github.com/repos/Codertocat/Hello-World/deployments/326191728",
      "id": 326191728,
      "node_id": "MDEwOkRlcGxveW1lbnQzMjYxOTE3Mjg=",
      "task": "deploy",
      "original_environment": "lab",
      "environment": "lab",
      "description": null,
      "created_at": "2021-02-18T08:22:48Z",
      "updated_at": "2021-02-18T09:47:16Z",
      "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments/326191728/statuses",
      "repository_url": "https://api.github.com/repos/Codertocat/Hello-World"
    }
  },
  "repository": {
    "id": 186853002,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
    "name": "Hello-World",
    "full_name": "Codertocat/Hello-World",
    "private": false,
    "owner": {
      "login": "Codertocat",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Codertocat/Hello-World",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Codertocat/Hello-World",
    "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
    "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
    "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
    "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
    "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
    "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
    "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
    "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
    "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
    "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
    "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
    "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
    "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
    "created_at": "2019-05-15T15:19:25Z",
    "updated_at": "2019-05-15T15:21:03Z",
    "pushed_at": "2019-05-15T15:20:57Z",
    "git_url": "git://github.com/Codertocat/Hello-World.git",
    "ssh_url": "git@github.com:Codertocat/Hello-World.git",
    "clone_url": "https://github.com/Codertocat/Hello-World.git",
    "svn_url": "https://github.com/Codertocat/Hello-World",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Ruby",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 1,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "Codertocat",
    "id": 21031067,
    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Codertocat",
    "html_url": "https://github.com/Codertocat",
    "followers_url": "https://api.github.com/users/Codertocat/followers",
    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
    "repos_url": "https://api.github.com/users/Codertocat/repos",
    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
    "type": "User",
    "site_admin": false
  }
}
''';

const String createString = '''
{
  "ref": "simple-branch",
  "ref_type": "branch",
  "master_branch": "master",
  "description": null,
  "pusher_type": "user",
  "repository": {
    "id": 186853002,
    "node_id": "MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=",
    "name": "Hello-World",
    "full_name": "Codertocat/Hello-World",
    "private": false,
    "owner": {
      "login": "Codertocat",
      "id": 21031067,
      "node_id": "MDQ6VXNlcjIxMDMxMDY3",
      "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Codertocat",
      "html_url": "https://github.com/Codertocat",
      "followers_url": "https://api.github.com/users/Codertocat/followers",
      "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
      "organizations_url": "https://api.github.com/users/Codertocat/orgs",
      "repos_url": "https://api.github.com/users/Codertocat/repos",
      "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Codertocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "html_url": "https://github.com/Codertocat/Hello-World",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Codertocat/Hello-World",
    "forks_url": "https://api.github.com/repos/Codertocat/Hello-World/forks",
    "keys_url": "https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Codertocat/Hello-World/teams",
    "hooks_url": "https://api.github.com/repos/Codertocat/Hello-World/hooks",
    "issue_events_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Codertocat/Hello-World/events",
    "assignees_url": "https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Codertocat/Hello-World/tags",
    "blobs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Codertocat/Hello-World/languages",
    "stargazers_url": "https://api.github.com/repos/Codertocat/Hello-World/stargazers",
    "contributors_url": "https://api.github.com/repos/Codertocat/Hello-World/contributors",
    "subscribers_url": "https://api.github.com/repos/Codertocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/Codertocat/Hello-World/subscription",
    "commits_url": "https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Codertocat/Hello-World/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Codertocat/Hello-World/merges",
    "archive_url": "https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Codertocat/Hello-World/downloads",
    "issues_url": "https://api.github.com/repos/Codertocat/Hello-World/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Codertocat/Hello-World/labels{/name}",
    "releases_url": "https://api.github.com/repos/Codertocat/Hello-World/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Codertocat/Hello-World/deployments",
    "created_at": "2019-05-15T15:19:25Z",
    "updated_at": "2019-05-15T15:20:41Z",
    "pushed_at": "2019-05-15T15:20:56Z",
    "git_url": "git://github.com/Codertocat/Hello-World.git",
    "ssh_url": "git@github.com:Codertocat/Hello-World.git",
    "clone_url": "https://github.com/Codertocat/Hello-World.git",
    "svn_url": "https://github.com/Codertocat/Hello-World",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Ruby",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 2,
    "license": null,
    "forks": 1,
    "open_issues": 2,
    "watchers": 0,
    "default_branch": "master"
  },
  "sender": {
    "login": "Codertocat",
    "id": 21031067,
    "node_id": "MDQ6VXNlcjIxMDMxMDY3",
    "avatar_url": "https://avatars1.githubusercontent.com/u/21031067?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Codertocat",
    "html_url": "https://github.com/Codertocat",
    "followers_url": "https://api.github.com/users/Codertocat/followers",
    "following_url": "https://api.github.com/users/Codertocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/Codertocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Codertocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Codertocat/subscriptions",
    "organizations_url": "https://api.github.com/users/Codertocat/orgs",
    "repos_url": "https://api.github.com/users/Codertocat/repos",
    "events_url": "https://api.github.com/users/Codertocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Codertocat/received_events",
    "type": "User",
    "site_admin": false
  }
}
''';

const String prBodyEditedEvent = '''
{
  "action": "edited",
  "number": 47609,
  "pull_request": {
    "url": "https://api.github.com/repos/flutter/engine/pulls/47609",
    "id": 1584723957,
    "node_id": "PR_kwDOAlZRSc5edPf1",
    "html_url": "https://github.com/flutter/engine/pull/47609",
    "diff_url": "https://github.com/flutter/engine/pull/47609.diff",
    "patch_url": "https://github.com/flutter/engine/pull/47609.patch",
    "issue_url": "https://api.github.com/repos/flutter/engine/issues/47609",
    "number": 47609,
    "state": "open",
    "locked": false,
    "title": "Upgrade Android SDK to 34 UpsideDownCake",
    "user": {
      "login": "gmackall",
      "id": 34871572,
      "node_id": "MDQ6VXNlcjM0ODcxNTcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gmackall",
      "html_url": "https://github.com/gmackall",
      "followers_url": "https://api.github.com/users/gmackall/followers",
      "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
      "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
      "organizations_url": "https://api.github.com/users/gmackall/orgs",
      "repos_url": "https://api.github.com/users/gmackall/repos",
      "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gmackall/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "~**This should not land until https://github.com/flutter/buildroot/pull/790 (re)lands, and I swap the buildroot url back to the latest commit.**~ Reland of PR to update buildroot at https://github.com/flutter/buildroot/pull/792. Upgrades to android api 34 Also: 1. Upgrades to java 17 in DEPS/ci",
    "created_at": "2023-11-02T17:09:59Z",
    "updated_at": "2023-11-08T21:00:47Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "8e5e3a59a5cba4239c542ed9a914899a246640b7",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [
      {
        "id": 246348935,
        "node_id": "MDU6TGFiZWwyNDYzNDg5MzU=",
        "url": "https://api.github.com/repos/flutter/engine/labels/platform-android",
        "name": "platform-android",
        "color": "A4C639",
        "default": false,
        "description": null
      }
    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/flutter/engine/pulls/47609/commits",
    "review_comments_url": "https://api.github.com/repos/flutter/engine/pulls/47609/comments",
    "review_comment_url": "https://api.github.com/repos/flutter/engine/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/flutter/engine/issues/47609/comments",
    "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/a6765b4c309aa082bbebade68e0c7ec308a1cc6c",
    "head": {
      "label": "gmackall:upgrade_to_android14",
      "ref": "upgrade_to_android14",
      "sha": "a6765b4c309aa082bbebade68e0c7ec308a1cc6c",
      "user": {
        "login": "gmackall",
        "id": 34871572,
        "node_id": "MDQ6VXNlcjM0ODcxNTcy",
        "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gmackall",
        "html_url": "https://github.com/gmackall",
        "followers_url": "https://api.github.com/users/gmackall/followers",
        "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
        "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
        "organizations_url": "https://api.github.com/users/gmackall/orgs",
        "repos_url": "https://api.github.com/users/gmackall/repos",
        "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gmackall/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 547558963,
        "node_id": "R_kgDOIKMWMw",
        "name": "engine",
        "full_name": "gmackall/engine",
        "private": false,
        "owner": {
          "login": "gmackall",
          "id": 34871572,
          "node_id": "MDQ6VXNlcjM0ODcxNTcy",
          "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gmackall",
          "html_url": "https://github.com/gmackall",
          "followers_url": "https://api.github.com/users/gmackall/followers",
          "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
          "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
          "organizations_url": "https://api.github.com/users/gmackall/orgs",
          "repos_url": "https://api.github.com/users/gmackall/repos",
          "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gmackall/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/gmackall/engine",
        "description": "The Flutter engine",
        "fork": true,
        "url": "https://api.github.com/repos/gmackall/engine",
        "forks_url": "https://api.github.com/repos/gmackall/engine/forks",
        "keys_url": "https://api.github.com/repos/gmackall/engine/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/gmackall/engine/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/gmackall/engine/teams",
        "hooks_url": "https://api.github.com/repos/gmackall/engine/hooks",
        "issue_events_url": "https://api.github.com/repos/gmackall/engine/issues/events{/number}",
        "events_url": "https://api.github.com/repos/gmackall/engine/events",
        "assignees_url": "https://api.github.com/repos/gmackall/engine/assignees{/user}",
        "branches_url": "https://api.github.com/repos/gmackall/engine/branches{/branch}",
        "tags_url": "https://api.github.com/repos/gmackall/engine/tags",
        "blobs_url": "https://api.github.com/repos/gmackall/engine/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/gmackall/engine/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/gmackall/engine/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/gmackall/engine/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/gmackall/engine/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/gmackall/engine/languages",
        "stargazers_url": "https://api.github.com/repos/gmackall/engine/stargazers",
        "contributors_url": "https://api.github.com/repos/gmackall/engine/contributors",
        "subscribers_url": "https://api.github.com/repos/gmackall/engine/subscribers",
        "subscription_url": "https://api.github.com/repos/gmackall/engine/subscription",
        "commits_url": "https://api.github.com/repos/gmackall/engine/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/gmackall/engine/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/gmackall/engine/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/gmackall/engine/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/gmackall/engine/contents/{+path}",
        "compare_url": "https://api.github.com/repos/gmackall/engine/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/gmackall/engine/merges",
        "archive_url": "https://api.github.com/repos/gmackall/engine/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/gmackall/engine/downloads",
        "issues_url": "https://api.github.com/repos/gmackall/engine/issues{/number}",
        "pulls_url": "https://api.github.com/repos/gmackall/engine/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/gmackall/engine/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/gmackall/engine/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/gmackall/engine/labels{/name}",
        "releases_url": "https://api.github.com/repos/gmackall/engine/releases{/id}",
        "deployments_url": "https://api.github.com/repos/gmackall/engine/deployments",
        "created_at": "2022-10-07T22:25:57Z",
        "updated_at": "2023-02-02T18:38:07Z",
        "pushed_at": "2023-11-08T20:57:02Z",
        "git_url": "git://github.com/gmackall/engine.git",
        "ssh_url": "git@github.com:gmackall/engine.git",
        "clone_url": "https://github.com/gmackall/engine.git",
        "svn_url": "https://github.com/gmackall/engine",
        "homepage": "https://flutter.dev",
        "size": 466778,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "C++",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause New or Revised License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "flutter:main",
      "ref": "main",
      "sha": "941e246d4851f652cf13312180174ebc9395fac4",
      "user": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 39211337,
        "node_id": "MDEwOlJlcG9zaXRvcnkzOTIxMTMzNw==",
        "name": "engine",
        "full_name": "flutter/engine",
        "private": false,
        "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/flutter/engine",
        "description": "The Flutter engine",
        "fork": false,
        "url": "https://api.github.com/repos/flutter/engine",
        "forks_url": "https://api.github.com/repos/flutter/engine/forks",
        "keys_url": "https://api.github.com/repos/flutter/engine/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/flutter/engine/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/flutter/engine/teams",
        "hooks_url": "https://api.github.com/repos/flutter/engine/hooks",
        "issue_events_url": "https://api.github.com/repos/flutter/engine/issues/events{/number}",
        "events_url": "https://api.github.com/repos/flutter/engine/events",
        "assignees_url": "https://api.github.com/repos/flutter/engine/assignees{/user}",
        "branches_url": "https://api.github.com/repos/flutter/engine/branches{/branch}",
        "tags_url": "https://api.github.com/repos/flutter/engine/tags",
        "blobs_url": "https://api.github.com/repos/flutter/engine/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/flutter/engine/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/flutter/engine/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/flutter/engine/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/flutter/engine/languages",
        "stargazers_url": "https://api.github.com/repos/flutter/engine/stargazers",
        "contributors_url": "https://api.github.com/repos/flutter/engine/contributors",
        "subscribers_url": "https://api.github.com/repos/flutter/engine/subscribers",
        "subscription_url": "https://api.github.com/repos/flutter/engine/subscription",
        "commits_url": "https://api.github.com/repos/flutter/engine/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/flutter/engine/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/flutter/engine/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/flutter/engine/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/flutter/engine/contents/{+path}",
        "compare_url": "https://api.github.com/repos/flutter/engine/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/flutter/engine/merges",
        "archive_url": "https://api.github.com/repos/flutter/engine/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/flutter/engine/downloads",
        "issues_url": "https://api.github.com/repos/flutter/engine/issues{/number}",
        "pulls_url": "https://api.github.com/repos/flutter/engine/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/flutter/engine/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/flutter/engine/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/flutter/engine/labels{/name}",
        "releases_url": "https://api.github.com/repos/flutter/engine/releases{/id}",
        "deployments_url": "https://api.github.com/repos/flutter/engine/deployments",
        "created_at": "2015-07-16T17:39:56Z",
        "updated_at": "2023-11-08T07:16:25Z",
        "pushed_at": "2023-11-08T21:00:38Z",
        "git_url": "git://github.com/flutter/engine.git",
        "ssh_url": "git@github.com:flutter/engine.git",
        "clone_url": "https://github.com/flutter/engine.git",
        "svn_url": "https://github.com/flutter/engine",
        "homepage": "https://flutter.dev",
        "size": 704170,
        "stargazers_count": 6848,
        "watchers_count": 6848,
        "language": "C++",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 5600,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 99,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause New or Revised License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "c-plus-plus"
        ],
        "visibility": "public",
        "forks": 5600,
        "open_issues": 99,
        "watchers": 6848,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": false,
        "allow_auto_merge": false,
        "delete_branch_on_merge": true,
        "allow_update_branch": true,
        "use_squash_pr_title_as_default": true,
        "squash_merge_commit_message": "PR_BODY",
        "squash_merge_commit_title": "PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609"
      },
      "html": {
        "href": "https://github.com/flutter/engine/pull/47609"
      },
      "issue": {
        "href": "https://api.github.com/repos/flutter/engine/issues/47609"
      },
      "comments": {
        "href": "https://api.github.com/repos/flutter/engine/issues/47609/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/flutter/engine/statuses/a6765b4c309aa082bbebade68e0c7ec308a1cc6c"
      }
    },
    "author_association": "MEMBER",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": true,
    "rebaseable": true,
    "mergeable_state": "clean",
    "merged_by": null,
    "comments": 4,
    "review_comments": 4,
    "maintainer_can_modify": true,
    "commits": 32,
    "additions": 83,
    "deletions": 77,
    "changed_files": 18
  },
  "changes": {
    "body": {
      "from": "**This should not land until https://github.com/flutter/buildroot/pull/790"
    }
  },
  "repository": {
    "id": 39211337,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTIxMTMzNw==",
    "name": "engine",
    "full_name": "flutter/engine",
    "private": false,
    "owner": {
      "login": "flutter",
      "id": 14101776,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
      "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flutter/engine",
    "description": "The Flutter engine",
    "fork": false,
    "url": "https://api.github.com/repos/flutter/engine",
    "forks_url": "https://api.github.com/repos/flutter/engine/forks",
    "keys_url": "https://api.github.com/repos/flutter/engine/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flutter/engine/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flutter/engine/teams",
    "hooks_url": "https://api.github.com/repos/flutter/engine/hooks",
    "issue_events_url": "https://api.github.com/repos/flutter/engine/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flutter/engine/events",
    "assignees_url": "https://api.github.com/repos/flutter/engine/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flutter/engine/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flutter/engine/tags",
    "blobs_url": "https://api.github.com/repos/flutter/engine/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flutter/engine/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flutter/engine/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flutter/engine/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flutter/engine/languages",
    "stargazers_url": "https://api.github.com/repos/flutter/engine/stargazers",
    "contributors_url": "https://api.github.com/repos/flutter/engine/contributors",
    "subscribers_url": "https://api.github.com/repos/flutter/engine/subscribers",
    "subscription_url": "https://api.github.com/repos/flutter/engine/subscription",
    "commits_url": "https://api.github.com/repos/flutter/engine/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flutter/engine/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flutter/engine/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flutter/engine/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flutter/engine/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flutter/engine/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flutter/engine/merges",
    "archive_url": "https://api.github.com/repos/flutter/engine/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flutter/engine/downloads",
    "issues_url": "https://api.github.com/repos/flutter/engine/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flutter/engine/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flutter/engine/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flutter/engine/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flutter/engine/labels{/name}",
    "releases_url": "https://api.github.com/repos/flutter/engine/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flutter/engine/deployments",
    "created_at": "2015-07-16T17:39:56Z",
    "updated_at": "2023-11-08T07:16:25Z",
    "pushed_at": "2023-11-08T21:00:38Z",
    "git_url": "git://github.com/flutter/engine.git",
    "ssh_url": "git@github.com:flutter/engine.git",
    "clone_url": "https://github.com/flutter/engine.git",
    "svn_url": "https://github.com/flutter/engine",
    "homepage": "https://flutter.dev",
    "size": 704170,
    "stargazers_count": 6848,
    "watchers_count": 6848,
    "language": "C++",
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 5600,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 99,
    "license": {
      "key": "bsd-3-clause",
      "name": "BSD 3-Clause New or Revised License",
      "spdx_id": "BSD-3-Clause",
      "url": "https://api.github.com/licenses/bsd-3-clause",
      "node_id": "MDc6TGljZW5zZTU="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "c-plus-plus"
    ],
    "visibility": "public",
    "forks": 5600,
    "open_issues": 99,
    "watchers": 6848,
    "default_branch": "main",
    "custom_properties": {

    }
  },
  "organization": {
    "login": "flutter",
    "id": 14101776,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
    "url": "https://api.github.com/orgs/flutter",
    "repos_url": "https://api.github.com/orgs/flutter/repos",
    "events_url": "https://api.github.com/orgs/flutter/events",
    "hooks_url": "https://api.github.com/orgs/flutter/hooks",
    "issues_url": "https://api.github.com/orgs/flutter/issues",
    "members_url": "https://api.github.com/orgs/flutter/members{/member}",
    "public_members_url": "https://api.github.com/orgs/flutter/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
    "description": "Flutter is Google's UI toolkit for building beautiful, natively compiled applications for mobile, web, desktop, and embedded devices from a single codebase."
  },
  "enterprise": {
    "id": 1732,
    "slug": "alphabet",
    "name": "Alphabet",
    "node_id": "MDEwOkVudGVycHJpc2UxNzMy",
    "avatar_url": "https://avatars.githubusercontent.com/b/1732?v=4",
    "description": "",
    "website_url": "https://abc.xyz/",
    "html_url": "https://github.com/enterprises/alphabet",
    "created_at": "2019-12-19T00:30:52Z",
    "updated_at": "2023-01-20T00:41:48Z"
  },
  "sender": {
    "login": "gmackall",
    "id": 34871572,
    "node_id": "MDQ6VXNlcjM0ODcxNTcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gmackall",
    "html_url": "https://github.com/gmackall",
    "followers_url": "https://api.github.com/users/gmackall/followers",
    "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
    "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
    "organizations_url": "https://api.github.com/users/gmackall/orgs",
    "repos_url": "https://api.github.com/users/gmackall/repos",
    "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gmackall/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 10381585,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTAzODE1ODU="
  }
}
''';

const String prBaseEditedEvent = '''
{
  "action": "edited",
  "number": 47609,
  "pull_request": {
    "url": "https://api.github.com/repos/flutter/engine/pulls/47609",
    "id": 1584723957,
    "node_id": "PR_kwDOAlZRSc5edPf1",
    "html_url": "https://github.com/flutter/engine/pull/47609",
    "diff_url": "https://github.com/flutter/engine/pull/47609.diff",
    "patch_url": "https://github.com/flutter/engine/pull/47609.patch",
    "issue_url": "https://api.github.com/repos/flutter/engine/issues/47609",
    "number": 47609,
    "state": "open",
    "locked": false,
    "title": "Upgrade Android SDK to 34 UpsideDownCake",
    "user": {
      "login": "gmackall",
      "id": 34871572,
      "node_id": "MDQ6VXNlcjM0ODcxNTcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gmackall",
      "html_url": "https://github.com/gmackall",
      "followers_url": "https://api.github.com/users/gmackall/followers",
      "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
      "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
      "organizations_url": "https://api.github.com/users/gmackall/orgs",
      "repos_url": "https://api.github.com/users/gmackall/repos",
      "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gmackall/received_events",
      "type": "User",
      "site_admin": false
    },
    "body": "~**This should not land until https://github.com/flutter/buildroot/pull/790 (re)lands, and I swap the buildroot url back to the latest commit.**~ Reland of PR to update buildroot at https://github.com/flutter/buildroot/pull/792. Upgrades to android api 34 Also: 1. Upgrades to java 17 in DEPS/ci",
    "created_at": "2023-11-02T17:09:59Z",
    "updated_at": "2023-11-08T21:00:47Z",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": "8e5e3a59a5cba4239c542ed9a914899a246640b7",
    "assignee": null,
    "assignees": [

    ],
    "requested_reviewers": [

    ],
    "requested_teams": [

    ],
    "labels": [
      {
        "id": 246348935,
        "node_id": "MDU6TGFiZWwyNDYzNDg5MzU=",
        "url": "https://api.github.com/repos/flutter/engine/labels/platform-android",
        "name": "platform-android",
        "color": "A4C639",
        "default": false,
        "description": null
      }
    ],
    "milestone": null,
    "draft": false,
    "commits_url": "https://api.github.com/repos/flutter/engine/pulls/47609/commits",
    "review_comments_url": "https://api.github.com/repos/flutter/engine/pulls/47609/comments",
    "review_comment_url": "https://api.github.com/repos/flutter/engine/pulls/comments{/number}",
    "comments_url": "https://api.github.com/repos/flutter/engine/issues/47609/comments",
    "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/a6765b4c309aa082bbebade68e0c7ec308a1cc6c",
    "head": {
      "label": "gmackall:upgrade_to_android14",
      "ref": "upgrade_to_android14",
      "sha": "a6765b4c309aa082bbebade68e0c7ec308a1cc6c",
      "user": {
        "login": "gmackall",
        "id": 34871572,
        "node_id": "MDQ6VXNlcjM0ODcxNTcy",
        "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/gmackall",
        "html_url": "https://github.com/gmackall",
        "followers_url": "https://api.github.com/users/gmackall/followers",
        "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
        "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
        "organizations_url": "https://api.github.com/users/gmackall/orgs",
        "repos_url": "https://api.github.com/users/gmackall/repos",
        "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
        "received_events_url": "https://api.github.com/users/gmackall/received_events",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 547558963,
        "node_id": "R_kgDOIKMWMw",
        "name": "engine",
        "full_name": "gmackall/engine",
        "private": false,
        "owner": {
          "login": "gmackall",
          "id": 34871572,
          "node_id": "MDQ6VXNlcjM0ODcxNTcy",
          "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/gmackall",
          "html_url": "https://github.com/gmackall",
          "followers_url": "https://api.github.com/users/gmackall/followers",
          "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
          "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
          "organizations_url": "https://api.github.com/users/gmackall/orgs",
          "repos_url": "https://api.github.com/users/gmackall/repos",
          "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
          "received_events_url": "https://api.github.com/users/gmackall/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/gmackall/engine",
        "description": "The Flutter engine",
        "fork": true,
        "url": "https://api.github.com/repos/gmackall/engine",
        "forks_url": "https://api.github.com/repos/gmackall/engine/forks",
        "keys_url": "https://api.github.com/repos/gmackall/engine/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/gmackall/engine/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/gmackall/engine/teams",
        "hooks_url": "https://api.github.com/repos/gmackall/engine/hooks",
        "issue_events_url": "https://api.github.com/repos/gmackall/engine/issues/events{/number}",
        "events_url": "https://api.github.com/repos/gmackall/engine/events",
        "assignees_url": "https://api.github.com/repos/gmackall/engine/assignees{/user}",
        "branches_url": "https://api.github.com/repos/gmackall/engine/branches{/branch}",
        "tags_url": "https://api.github.com/repos/gmackall/engine/tags",
        "blobs_url": "https://api.github.com/repos/gmackall/engine/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/gmackall/engine/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/gmackall/engine/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/gmackall/engine/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/gmackall/engine/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/gmackall/engine/languages",
        "stargazers_url": "https://api.github.com/repos/gmackall/engine/stargazers",
        "contributors_url": "https://api.github.com/repos/gmackall/engine/contributors",
        "subscribers_url": "https://api.github.com/repos/gmackall/engine/subscribers",
        "subscription_url": "https://api.github.com/repos/gmackall/engine/subscription",
        "commits_url": "https://api.github.com/repos/gmackall/engine/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/gmackall/engine/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/gmackall/engine/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/gmackall/engine/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/gmackall/engine/contents/{+path}",
        "compare_url": "https://api.github.com/repos/gmackall/engine/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/gmackall/engine/merges",
        "archive_url": "https://api.github.com/repos/gmackall/engine/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/gmackall/engine/downloads",
        "issues_url": "https://api.github.com/repos/gmackall/engine/issues{/number}",
        "pulls_url": "https://api.github.com/repos/gmackall/engine/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/gmackall/engine/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/gmackall/engine/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/gmackall/engine/labels{/name}",
        "releases_url": "https://api.github.com/repos/gmackall/engine/releases{/id}",
        "deployments_url": "https://api.github.com/repos/gmackall/engine/deployments",
        "created_at": "2022-10-07T22:25:57Z",
        "updated_at": "2023-02-02T18:38:07Z",
        "pushed_at": "2023-11-08T20:57:02Z",
        "git_url": "git://github.com/gmackall/engine.git",
        "ssh_url": "git@github.com:gmackall/engine.git",
        "clone_url": "https://github.com/gmackall/engine.git",
        "svn_url": "https://github.com/gmackall/engine",
        "homepage": "https://flutter.dev",
        "size": 466778,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "C++",
        "has_issues": false,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause New or Revised License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": true,
        "allow_rebase_merge": true,
        "allow_auto_merge": false,
        "delete_branch_on_merge": false,
        "allow_update_branch": false,
        "use_squash_pr_title_as_default": false,
        "squash_merge_commit_message": "COMMIT_MESSAGES",
        "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "base": {
      "label": "flutter:main",
      "ref": "main",
      "sha": "941e246d4851f652cf13312180174ebc9395fac4",
      "user": {
        "login": "flutter",
        "id": 14101776,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/flutter",
        "html_url": "https://github.com/flutter",
        "followers_url": "https://api.github.com/users/flutter/followers",
        "following_url": "https://api.github.com/users/flutter/following{/other_user}",
        "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
        "organizations_url": "https://api.github.com/users/flutter/orgs",
        "repos_url": "https://api.github.com/users/flutter/repos",
        "events_url": "https://api.github.com/users/flutter/events{/privacy}",
        "received_events_url": "https://api.github.com/users/flutter/received_events",
        "type": "Organization",
        "site_admin": false
      },
      "repo": {
        "id": 39211337,
        "node_id": "MDEwOlJlcG9zaXRvcnkzOTIxMTMzNw==",
        "name": "engine",
        "full_name": "flutter/engine",
        "private": false,
        "owner": {
          "login": "flutter",
          "id": 14101776,
          "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
          "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/flutter",
          "html_url": "https://github.com/flutter",
          "followers_url": "https://api.github.com/users/flutter/followers",
          "following_url": "https://api.github.com/users/flutter/following{/other_user}",
          "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
          "organizations_url": "https://api.github.com/users/flutter/orgs",
          "repos_url": "https://api.github.com/users/flutter/repos",
          "events_url": "https://api.github.com/users/flutter/events{/privacy}",
          "received_events_url": "https://api.github.com/users/flutter/received_events",
          "type": "Organization",
          "site_admin": false
        },
        "html_url": "https://github.com/flutter/engine",
        "description": "The Flutter engine",
        "fork": false,
        "url": "https://api.github.com/repos/flutter/engine",
        "forks_url": "https://api.github.com/repos/flutter/engine/forks",
        "keys_url": "https://api.github.com/repos/flutter/engine/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/flutter/engine/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/flutter/engine/teams",
        "hooks_url": "https://api.github.com/repos/flutter/engine/hooks",
        "issue_events_url": "https://api.github.com/repos/flutter/engine/issues/events{/number}",
        "events_url": "https://api.github.com/repos/flutter/engine/events",
        "assignees_url": "https://api.github.com/repos/flutter/engine/assignees{/user}",
        "branches_url": "https://api.github.com/repos/flutter/engine/branches{/branch}",
        "tags_url": "https://api.github.com/repos/flutter/engine/tags",
        "blobs_url": "https://api.github.com/repos/flutter/engine/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/flutter/engine/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/flutter/engine/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/flutter/engine/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/flutter/engine/languages",
        "stargazers_url": "https://api.github.com/repos/flutter/engine/stargazers",
        "contributors_url": "https://api.github.com/repos/flutter/engine/contributors",
        "subscribers_url": "https://api.github.com/repos/flutter/engine/subscribers",
        "subscription_url": "https://api.github.com/repos/flutter/engine/subscription",
        "commits_url": "https://api.github.com/repos/flutter/engine/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/flutter/engine/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/flutter/engine/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/flutter/engine/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/flutter/engine/contents/{+path}",
        "compare_url": "https://api.github.com/repos/flutter/engine/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/flutter/engine/merges",
        "archive_url": "https://api.github.com/repos/flutter/engine/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/flutter/engine/downloads",
        "issues_url": "https://api.github.com/repos/flutter/engine/issues{/number}",
        "pulls_url": "https://api.github.com/repos/flutter/engine/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/flutter/engine/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/flutter/engine/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/flutter/engine/labels{/name}",
        "releases_url": "https://api.github.com/repos/flutter/engine/releases{/id}",
        "deployments_url": "https://api.github.com/repos/flutter/engine/deployments",
        "created_at": "2015-07-16T17:39:56Z",
        "updated_at": "2023-11-08T07:16:25Z",
        "pushed_at": "2023-11-08T21:00:38Z",
        "git_url": "git://github.com/flutter/engine.git",
        "ssh_url": "git@github.com:flutter/engine.git",
        "clone_url": "https://github.com/flutter/engine.git",
        "svn_url": "https://github.com/flutter/engine",
        "homepage": "https://flutter.dev",
        "size": 704170,
        "stargazers_count": 6848,
        "watchers_count": 6848,
        "language": "C++",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 5600,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 99,
        "license": {
          "key": "bsd-3-clause",
          "name": "BSD 3-Clause New or Revised License",
          "spdx_id": "BSD-3-Clause",
          "url": "https://api.github.com/licenses/bsd-3-clause",
          "node_id": "MDc6TGljZW5zZTU="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
          "c-plus-plus"
        ],
        "visibility": "public",
        "forks": 5600,
        "open_issues": 99,
        "watchers": 6848,
        "default_branch": "main",
        "allow_squash_merge": true,
        "allow_merge_commit": false,
        "allow_rebase_merge": false,
        "allow_auto_merge": false,
        "delete_branch_on_merge": true,
        "allow_update_branch": true,
        "use_squash_pr_title_as_default": true,
        "squash_merge_commit_message": "PR_BODY",
        "squash_merge_commit_title": "PR_TITLE",
        "merge_commit_message": "PR_TITLE",
        "merge_commit_title": "MERGE_MESSAGE"
      }
    },
    "_links": {
      "self": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609"
      },
      "html": {
        "href": "https://github.com/flutter/engine/pull/47609"
      },
      "issue": {
        "href": "https://api.github.com/repos/flutter/engine/issues/47609"
      },
      "comments": {
        "href": "https://api.github.com/repos/flutter/engine/issues/47609/comments"
      },
      "review_comments": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609/comments"
      },
      "review_comment": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/comments{/number}"
      },
      "commits": {
        "href": "https://api.github.com/repos/flutter/engine/pulls/47609/commits"
      },
      "statuses": {
        "href": "https://api.github.com/repos/flutter/engine/statuses/a6765b4c309aa082bbebade68e0c7ec308a1cc6c"
      }
    },
    "author_association": "MEMBER",
    "auto_merge": null,
    "active_lock_reason": null,
    "merged": false,
    "mergeable": true,
    "rebaseable": true,
    "mergeable_state": "clean",
    "merged_by": null,
    "comments": 4,
    "review_comments": 4,
    "maintainer_can_modify": true,
    "commits": 32,
    "additions": 83,
    "deletions": 77,
    "changed_files": 18
  },
  "changes": {
    "base": {
      "ref": {
        "from": "main"
      },
      "sha": {
        "from": "b3af5d64d3e6e2110b07d71909fc432537339659"
      }
    }
  },
  "repository": {
    "id": 39211337,
    "node_id": "MDEwOlJlcG9zaXRvcnkzOTIxMTMzNw==",
    "name": "engine",
    "full_name": "flutter/engine",
    "private": false,
    "owner": {
      "login": "flutter",
      "id": 14101776,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
      "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/flutter",
      "html_url": "https://github.com/flutter",
      "followers_url": "https://api.github.com/users/flutter/followers",
      "following_url": "https://api.github.com/users/flutter/following{/other_user}",
      "gists_url": "https://api.github.com/users/flutter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/flutter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/flutter/subscriptions",
      "organizations_url": "https://api.github.com/users/flutter/orgs",
      "repos_url": "https://api.github.com/users/flutter/repos",
      "events_url": "https://api.github.com/users/flutter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/flutter/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/flutter/engine",
    "description": "The Flutter engine",
    "fork": false,
    "url": "https://api.github.com/repos/flutter/engine",
    "forks_url": "https://api.github.com/repos/flutter/engine/forks",
    "keys_url": "https://api.github.com/repos/flutter/engine/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/flutter/engine/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/flutter/engine/teams",
    "hooks_url": "https://api.github.com/repos/flutter/engine/hooks",
    "issue_events_url": "https://api.github.com/repos/flutter/engine/issues/events{/number}",
    "events_url": "https://api.github.com/repos/flutter/engine/events",
    "assignees_url": "https://api.github.com/repos/flutter/engine/assignees{/user}",
    "branches_url": "https://api.github.com/repos/flutter/engine/branches{/branch}",
    "tags_url": "https://api.github.com/repos/flutter/engine/tags",
    "blobs_url": "https://api.github.com/repos/flutter/engine/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/flutter/engine/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/flutter/engine/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/flutter/engine/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/flutter/engine/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/flutter/engine/languages",
    "stargazers_url": "https://api.github.com/repos/flutter/engine/stargazers",
    "contributors_url": "https://api.github.com/repos/flutter/engine/contributors",
    "subscribers_url": "https://api.github.com/repos/flutter/engine/subscribers",
    "subscription_url": "https://api.github.com/repos/flutter/engine/subscription",
    "commits_url": "https://api.github.com/repos/flutter/engine/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/flutter/engine/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/flutter/engine/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/flutter/engine/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/flutter/engine/contents/{+path}",
    "compare_url": "https://api.github.com/repos/flutter/engine/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/flutter/engine/merges",
    "archive_url": "https://api.github.com/repos/flutter/engine/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/flutter/engine/downloads",
    "issues_url": "https://api.github.com/repos/flutter/engine/issues{/number}",
    "pulls_url": "https://api.github.com/repos/flutter/engine/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/flutter/engine/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/flutter/engine/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/flutter/engine/labels{/name}",
    "releases_url": "https://api.github.com/repos/flutter/engine/releases{/id}",
    "deployments_url": "https://api.github.com/repos/flutter/engine/deployments",
    "created_at": "2015-07-16T17:39:56Z",
    "updated_at": "2023-11-08T07:16:25Z",
    "pushed_at": "2023-11-08T21:00:38Z",
    "git_url": "git://github.com/flutter/engine.git",
    "ssh_url": "git@github.com:flutter/engine.git",
    "clone_url": "https://github.com/flutter/engine.git",
    "svn_url": "https://github.com/flutter/engine",
    "homepage": "https://flutter.dev",
    "size": 704170,
    "stargazers_count": 6848,
    "watchers_count": 6848,
    "language": "C++",
    "has_issues": false,
    "has_projects": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 5600,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 99,
    "license": {
      "key": "bsd-3-clause",
      "name": "BSD 3-Clause New or Revised License",
      "spdx_id": "BSD-3-Clause",
      "url": "https://api.github.com/licenses/bsd-3-clause",
      "node_id": "MDc6TGljZW5zZTU="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "c-plus-plus"
    ],
    "visibility": "public",
    "forks": 5600,
    "open_issues": 99,
    "watchers": 6848,
    "default_branch": "main",
    "custom_properties": {

    }
  },
  "organization": {
    "login": "flutter",
    "id": 14101776,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0MTAxNzc2",
    "url": "https://api.github.com/orgs/flutter",
    "repos_url": "https://api.github.com/orgs/flutter/repos",
    "events_url": "https://api.github.com/orgs/flutter/events",
    "hooks_url": "https://api.github.com/orgs/flutter/hooks",
    "issues_url": "https://api.github.com/orgs/flutter/issues",
    "members_url": "https://api.github.com/orgs/flutter/members{/member}",
    "public_members_url": "https://api.github.com/orgs/flutter/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/14101776?v=4",
    "description": "Flutter is Google's UI toolkit for building beautiful, natively compiled applications for mobile, web, desktop, and embedded devices from a single codebase."
  },
  "enterprise": {
    "id": 1732,
    "slug": "alphabet",
    "name": "Alphabet",
    "node_id": "MDEwOkVudGVycHJpc2UxNzMy",
    "avatar_url": "https://avatars.githubusercontent.com/b/1732?v=4",
    "description": "",
    "website_url": "https://abc.xyz/",
    "html_url": "https://github.com/enterprises/alphabet",
    "created_at": "2019-12-19T00:30:52Z",
    "updated_at": "2023-01-20T00:41:48Z"
  },
  "sender": {
    "login": "gmackall",
    "id": 34871572,
    "node_id": "MDQ6VXNlcjM0ODcxNTcy",
    "avatar_url": "https://avatars.githubusercontent.com/u/34871572?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/gmackall",
    "html_url": "https://github.com/gmackall",
    "followers_url": "https://api.github.com/users/gmackall/followers",
    "following_url": "https://api.github.com/users/gmackall/following{/other_user}",
    "gists_url": "https://api.github.com/users/gmackall/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/gmackall/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/gmackall/subscriptions",
    "organizations_url": "https://api.github.com/users/gmackall/orgs",
    "repos_url": "https://api.github.com/users/gmackall/repos",
    "events_url": "https://api.github.com/users/gmackall/events{/privacy}",
    "received_events_url": "https://api.github.com/users/gmackall/received_events",
    "type": "User",
    "site_admin": false
  },
  "installation": {
    "id": 10381585,
    "node_id": "MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMTAzODE1ODU="
  }
}
''';
