name: Auto-Release on PR Merge

# Runs when a PR merges. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges
on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container: dart:2.14.4

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          ref: master
      - name: Release
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          export GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}
          export MACHINE_GITHUB_API_TOKEN=${{secrets.MACHINE_GITHUB_API_TOKEN}}
          pub get
          pub global activate cider
          dart tool/auto_release_on_merge.dart ${{github.repository}} ${{github.event.pull_request.number}}
          