name: Require semver:* and unreleased Label
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: buildsville/add-remove-label@v2.0.0
        if: github.event.action == 'opened'
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: Unreleased
          type: add
      # - uses: mheap/github-action-required-labels@v3
      #   with:
      #     mode: exactly
      #     count: 1
      #     labels: "semver:patch, semver:minor, semver:major"
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     add_comment: Add a semantic version label (semver:patch semver:minor semver:major)
      # - uses: mheap/github-action-required-labels@v3
      #   with:
      #     mode: exactly
      #     count: 1
      #     labels: "unreleased"
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     add_comment: The unrelease label is required to track which PRs have yet to be released.
